### PR TITLE
feat(coinbase): coinbase pay card shows only when adding funds

### PR DESCRIPTION
**Pull request by awtsui**
### Description

A bug was found during 1.37 Bugapalooza where the Coinbase Pay card was visible in the withdraw flow.

This PR adds logic to limit Coinbase Pay card to the add funds flow.

https://user-images.githubusercontent.com/57046916/181386954-7757096c-d26a-4590-a42a-da830cd3f93d.mp4

### Other changes

N/A

### Tested

Screen recording above was taken on a mainnet build with Coinbase Pay feature flag turned on locally.

Added a unit test to check for coinbase pay card's visibility during both cash in and cash out flows.

### How others should test

Perform the following steps with the coinbsePayEnabled feature flag turned on.
Steps:
1. Navigate to the Withdraw Funds flow.
2. Select CELO and an available amount. 
3. Check if coinbase pay card is visible on Select Withdraw Method screen. 

Expected behavior:
Coinbase pay card should not be visible on Select Withdraw Method screen

### Related issues

N/A

### Backwards compatibility

N/A

### CODE REVIEW

**Comment by cajubelt** [comment]
the "steps to test" don't align with the change that's made here-- there isn't anything in those steps about how to verify the fix to the select providers screen when withdrawing

**Review by cajubelt — APPROVED** [review]
looks good, but make sure to update the PR description with test steps that test what's in this fix

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on latest iOS Test Flight build V: 1.38.0 and updated status in Test rails

**Observation :** Coinbase pay is not seen in withdraw CELO flow on select withdraw method page 

**Test Rail link:**
**iOS 14:** https://valoraapp.testrail.io/index.php?/tests/view/57037

**Device :** iPhone 12(14.7.1)

CC: @awtsui 

Thanks.!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above task on Android Internal Release Build V:1.38.0 and updated status in Test rails

**Test Rail links:**
**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/57051

Device : Google Pixel 2XL (11.0)

CC: @awtsui
Thanks.!!

**Pull request merged**
