### PR TITLE
Update dapps bottom screen text

### PR DESCRIPTION
**Pull request by MuckT**
### Description

Updates the dapps bottom screen text to be appropriate for the in app browser.

### Other changes

N/A

### Tested

Tested locally. 

### How others should test

From the Dapps page tap a Dapp and observe bottom sheet text. It should read:  `{{dappName}} is an external application`.

### Related issues

N/A

### Backwards compatibility

Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]

**Comment by MuckT** [comment]
@Mergifyio refresh

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Test Flight Alfajores Build V 1.29.2 and Android Alfajores Build V 1.29.2 & updated status in test rails.

**Test rail links:**

**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/22229
**Android 12:** https://valoraapp.testrail.io/index.php?/tests/view/22214
**iOS13:** https://valoraapp.testrail.io/index.php?/tests/view/22259
**iOS14:** https://valoraapp.testrail.io/index.php?/tests/view/22244

**Devices:** Google Pixel 2XL (11.0), iPhone SE 2020 (14.8.1), iPhone 7 (13.3), Google Pixel 4a (12.0)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Test Flight Release Build V 1.30.1 & updated status in test rails.

**Test rail link:**
**iOS15:** https://valoraapp.testrail.io/index.php?/tests/view/27234

**Device:** iPhone 13 mini(15.1.1)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Test Flight Release Build V 1.30.1 & updated status in test rails.

Test rail link:
iOS14: https://valoraapp.testrail.io/index.php?/tests/view/27327
Device: iPhone 12(14.7.1)

Thanks..!!

**Pull request merged**
