### PR TITLE
chore: farewell geth

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This fully removes the geth light client from the codebase 💥 

I know it's a big PR, I mostly only deleted code and and did some very light refactor following the removal of dead code branches (most of them in `web3/contracts.ts` and `web3/saga.ts`).

### Tested

- Updated tests

### How others should test

There should be no behavior change to the app. The app should work exactly like before.

### Related issues

- #2392

### Backwards compatibility

Yes

### CODE REVIEW

**Review by kathaypacific — APPROVED** [review]
🚀 LGTM!

relevant 🙈 https://twitter.com/iamdevloper/status/851445899008106496?s=20&t=5jrBGHtEF27QC1gY8xMFXQ

**Comment by jeanregisser** [comment]
@mergifyio refresh

**Comment by ValoraQA** [comment]
Hey @MuckT we can cover the above PR and check for Abnormality within the app while performing BVT and regression testing 
we will comment accordingly and provide observation if found any

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above PR while performing BVT's and here are the below links for the same

**Test Rail links:**
**Android 10 :** https://valoraapp.testrail.io/index.php?/runs/view/158&group_by=cases:section_id&group_order=asc
**Android 12:** https://valoraapp.testrail.io/index.php?/runs/view/159&group_by=cases:section_id&group_order=asc
**iOS 14:** https://valoraapp.testrail.io/index.php?/runs/view/161&group_by=cases:section_id&group_order=asc
**iOS 15 :** https://valoraapp.testrail.io/index.php?/runs/view/160&group_by=cases:section_id&group_order=asc

**Devices :** iPhone 13mini (15.1.1), iPhone 12(14.7.1), Google Pixel 4a(12.0), Google Pixel XL (10.0)

**CC**: @jeanregisser 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above PR while performing Regression testing and here are the below links for the same

**Test Rail links:**
**Android 12:** https://valoraapp.testrail.io/index.php?/runs/view/167&group_by=cases:section_id&group_order=asc
**iOS 15 :** https://valoraapp.testrail.io/index.php?/runs/view/166&group_by=cases:section_id&group_order=asc

**Devices :** iPhone 13 mini (15.1.1), Google Pixel 4a(12.0)]

**CC:** @jeanregisser

Thanks..!!

**Pull request merged**
