### PR TITLE
Send usability feedback

### LINKED ISSUE #1657: Product Design QA Updates
A few updates from usability testing & design QA. Includes things like: 

Figma link: https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Support-for-Multiple-Tokens?node-id=1459%3A38985

### PR DESCRIPTION
**Pull request by MuckT**
### Description

This PR covers the main points from the [send usability feedback](https://www.figma.com/file/8USELhisKuP1YlCt95WrD2/Support-for-Multiple-Tokens?node-id=1459%3A38985). 
- Adjusted the placement and styles of the max and swap buttons
- Adjusted the color of the review button.
- Reseting the input amount to zero when swapping tokens might require a larger refactor: any advice would be appreciated.

### Other changes

- nit spelling fixes

### Tested

This was tested locally on iOS and Android.

### How others should test

- Review the requirements from #1657 and the Figma file in that ticket.
- View the send screen on various sized devices.

### Related issues

- Fixes #1657 

### Backwards compatibility

Yes

### Screenshots
<div>
  
  
</div>

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Looks great! 🤩

**Comment by MuckT** [comment]
@jeanregisser would you be able to re-review? I had to make a few changes after some other PR's went in prior to this. Thanks!

**Review by jeanregisser — APPROVED** [review]
Great! 👍

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using iOS Testflight Nightly Build V1.24.0 & updated the status in below sheet.
**Note:** We are blocked to verify this issue in Android Nightly build V1.24.0, As the Application is crashing on app launch.

**Sheet Link:**
https://docs.google.com/spreadsheets/d/1LcYXmQcuLTBIHZrzUjoYaUvnzisq2ReRvxVwmn-xGEA/edit#gid=215230785

**New Bug:** [Link](https://github.com/valora-inc/wallet/issues/1789)
**Devices:** iPhone 13 mini (15.1.1), iPhone 12 (14.7.1)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest iOS Test Flight Release Build V:1.25.1 and updated the status in test rails

**Sheet link** : https://valoraapp.testrail.io/index.php?/runs/view/19&group_by=cases:section_id&group_order=asc

**Observation** : Amount is not getting reset to 0 when user selects other token from the dropdown and we have raised bug for it
[Bug link](https://github.com/valora-inc/wallet/issues/1880)

**Devices** : iPhone 7 (13.3)
Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android Internal Release Build V:1.25.2 and updated the status in test rails

**Test rail link** :
**Android 10:** https://valoraapp.testrail.io/index.php?/tests/view/7052&group_by=cases:section_id&group_order=asc&group_id=30

**Observation**: Amount is not getting reset to 0 when user selects other token from the dropdown and we have raised bug for it

[Bug Link](https://github.com/valora-inc/wallet/issues/1880)

**Devices** : Samsung Galaxy M40(10.0)
Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android Internal Release Build V:1.25.2 and updated the status in test rails

**Test rail link :**
**Android 8:** https://valoraapp.testrail.io/index.php?/tests/view/7115&group_by=cases:section_id&group_order=asc&group_id=30

**Observation:**

1. Amount is not getting reset to 0 when user selects other token from the dropdown and we have raised [bug](https://github.com/valora-inc/wallet/issues/1880) for it.
2. Swap button appear on enter amount screen when user have only single currency cUSD balance, As it appears in application, but it is not displayed in enter amount page in figma screens and we have raised [query](https://github.com/valora-inc/wallet/issues/1924) for it.

**Devices** : Samsung Galaxy A8+(8.0)
Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task on Latest Android Internal Release Build V:1.25.2 and updated the status in test rails

**Test rail link :**
**Android 9:**  https://valoraapp.testrail.io/index.php?/tests/view/7439

**Observations:**
1. Amount is not getting reset to 0 when user selects other token from the dropdown and we have raised [bug](https://github.com/valora-inc/wallet/issues/1880) for it.
2. Swap button appear on enter amount screen when user have only single currency cUSD balance, As it appears in application, but it is not displayed in enter amount page in figma screens and we have raised [query](https://github.com/valora-inc/wallet/issues/1924) for it.

**Devices:** Redmi Note 5 Pro (9.0)
Thanks..!!

**Pull request merged**
