### PR TITLE
Show the invited user's name in the invite modal

### LINKED ISSUE #1275: {{name}} variable in send & invite dialog populates as "Send to phone number"
The copy here is showing "Send to phone number" as the name of the user when I tried to invite someone only with phone number. 

We want {{name}} to be either a name pulled from contacts or just the phone number.

### PR DESCRIPTION
**Pull request by gnardini**
### Description

The invite modal is currently showing 'Send to Phone Number' in the modal instead of the name of the contact or the phone number. Also, the name is not being passed to the title.

This fixes it by passing nothing at all if we don't have a phone number's contact so that it uses the phone number ad display instead of the 'Send to Phone Number' text.

Screenshot when inviting contact:
Screen Shot 2021-11-19 at 20 21 51

Screenshot when inviting non-contact phone number:
Screen Shot 2021-11-22 at 04 15 41

### Other changes

N/A

### Tested

Manually and updated a snapshot test

### How others should test

Invite contacts in the contact list or a random number and see that the copy is as expected.

### Related issues

- Fixes #1275

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Thanks! 👍

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in latest Android Internal build V:1.22.2 and updated the status in G sheet

**Link :** https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=154665218

**Observation :** Contact name and contact number are seen properly on the pop up appearing after clicking on Send and Invite button

**Attachments :** [contact_name_proper.mp4](https://drive.google.com/file/d/1GZUhdNaJ1jHyulNPHw2cqdq88HQqScmy/view?usp=sharing), [contact_number_proper.mp4](https://drive.google.com/file/d/1Gdf3CQ1UJ14uTRy40HZxr0t7Dl1hurRL/view?usp=sharing)

**Verified on Devices :** OnePlus 7T(11.0), Redmi Note 8(9.0)

**CC** : @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in the latest Android Internal build V:1.22.2 and updated the status in below G sheet

**Gsheet Link:** https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=154665218&range=Q3

**Verified on Devices** :  Samsung Galaxy J5 Prime(8.0)

CC : @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in the latest Android Internal build V:1.22.2 &  Test Flight build V:1.22.2 and updated the status in the below G sheet

**Gsheet Link:** https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=154665218&range=S3
**Verified on Devices :** iPhone XR (14.6), Samsung Galaxy A21s (10.0)

CC : @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified the above issue in the latest Android Internal build V:1.22.3 & Test flight build V:1.22.3 and updated the status in test quality tool.

**Test Quality Tool Links:**
**Android 12:** https://valora.testquality.com/project/12128/plan/23022/run/153500/result/2591360 
**iOS 15:** https://valora.testquality.com/project/12128/plan/23022/run/153500/result/2591220
Devices: Google Pixel 4a(12), iPhone 8(15.1)
CC: @gnardini
Thanks..!!

**Pull request merged**
