### PR TITLE
fix(kyc): Update KYC status required for M2

### PR DESCRIPTION
**Pull request by jophish**
### Description

M2 is currently blocked behing a user's KYC status being `Completed`, when it should actually be `Approved`. This PR updates the required KYC status for a user to link their bank account.

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### How others should test

_Does this need to be tested by QA in the next release cycle? If so please give a brief explanation of how to test these changes._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Review by cajubelt — APPROVED** [review]
A'd, conditional on that snapshot test getting updated (please update the title too)

**Review by jh2oman — APPROVED** [review]
^ What Charlie said

**Review by lisaqyli — APPROVED** [review]

**Comment by ValoraQA** [comment]
Hey @MuckT  since "how other should test" has a statement "Does this need to be tested by QA in the next release cycle? If so please give a brief explanation of how to test these changes." so please provide more information about we can test the Pr , so we can write test cases, perform it and share feedback accordingly

Thanks..!!

**Comment by MuckT** [comment]
@jophish does this need to be tested by QA for the 1.26.0 release?

**Pull request merged**
