### PR TITLE
Fix bidali modal not triggered

### LINKED ISSUE #1521: Continuous loading appears on “Awaiting Payment” screen in Bidali page & User is blocked to buy gift card.
**Frequency:** 100%

**Repro on build version:** iOS Alfajores V1.22.1
**Repro on devices:** iPhone 12 (15.0), iPhone 6+ (12.5.4)

**Does Not Repro on build version:** iOS Alfajores 1.21.0
**Does Not Repro on devices:** iPhone 12 (15)
**Note:** For android alfa jores build V1.22.1 is not available.

**Pre-condition:** 
1. User must have installed the app and completed onboarding flow.
2. User must have sufficient balance in the account.
3. User must be on bidali screen. 

**Repro Steps:**
1. Tap on any brand.
2.  Select any option of gift card amount.
3. Tap on “Purchase” button.
4. Enter valid email address.
5. Tap on “Next” button & Observe.

**Current Behavior:** Continuous loading appears on “Awaiting Payment” screen in bidali page & User is blocked to buy gift card.

**Expected Behavior:**  Continuous loading must not appear on “Awaiting Payment” screen in bidali page & User must be able submit order.

**Impact:** Bad user experience as user is blocked to submit order

**Attachment:** [Not able to buy Gift Card.mp4](https://drive.google.com/file/d/1UKgG6EXSycVQ_rXZ83tTGbcjt_jG9YUX/view?usp=sharing)

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

The SendConfirmation was refactored into `SendConfirmation` (multi token) and `SendConfirmationLegacy` (previous impl).
However `SendConfirmationModalLegacy` was not added back. This fixes it.

### Tested

Manually.

### How others should test

Bidali payment modal is displayed.

### Related issues

- Fixes #1521

### Backwards compatibility

Yes

### CODE REVIEW

**Review by kathaypacific — APPROVED** [review]
LGTM 🚢

**Review by gnardini — APPROVED** [review]
😢

**Comment by ValoraQA** [comment]
Hey, @MuckT We have blocked to this issue as we are not able to see Alfajores build V1.22.1 for Android. Can you please do the needful ? 
**Gsheet Link for reference:**  https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=179256674&range=O3
**Checked for Alfajores build on Devices:** OnePlus 7T(11.0), Redmi Note 8(9.0)
CC: @jeanregisser 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey, @MuckT We have blocked to this issue as we are not able to see Alfajores build V1.22.1 for Android. Can you please do the needful ?
**Gsheet Link for reference:** https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=179256674&range=Q3
**Checked for Alfajores build on Devices:**  Samsung Galaxy J5 prime(8.0)
CC: @jeanregisser
Thanks..!!

**Comment by ValoraQA** [comment]
Hey, @MuckT We have verified this issue using Alfajores build V1.22.2 for iOS & updated status in Gsheet. Also, we have blocked to this issue as not able to see Alfajores build V1.22.1 for Android. Can you please do the needful ?
**Gsheet Link for reference:** https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=179256674&range=R3
**Checked for Android Alfajores build on Devices:** Samsung Galaxy A21s (10.0)
**Verified on the iOS device:**  iPhone XR (14.6)
CC: @jeanregisser
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified the above issue in the latest iOS Alfa jores build V:1.22.3 and updated the status in test quality tool.
**NOTE:** Also, we are blocked to verify this issue as not able to see Alfajores build V1.22.3 for Android.

**Test Quality Tool Links**
**iOS 15:** https://valora.testquality.com/project/12128/plan/23022/run/153500/result/2591228
Devices: iPhone 8(15.1)
CC: @gnardini
Thanks..!!

**Pull request merged**
