### PR TITLE
Fix pending invite item in feed

### LINKED ISSUE #1491: Confirming invites display incorrectly in feed
###Current behavior
After inviting a user while the confirmation is pending invites display a large incorrect value in the feed.

### Desired behavior
While confirmation is occurring invites should display the correct value or no value at all; invite rewards should not display a large incorrect value.

### Steps to Reproduce
1. On an existing account with a balance send an invite to a new user
2. Complete invite flow and observe transaction in the feed while pending.

### Versions
v1.22.1x

### PR DESCRIPTION
**Pull request by gnardini**
### Description

the pending item in the feed after sending an invite was showing up with the wei amount (so for cUSD/cEUR with 18 decimals was showing `value * 1e18`), which caused confusion. Switched to use the right amount.

### Other changes

N/A

### Tested

Manually and added a test

### How others should test

Send an invite and check that the 'confirming' item in the feed shows the correct number.

### Related issues

- Fixes #1491 and #1495

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Good catch! 👍

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in latest Android Internal build V:1.22.2 and updated the status in G sheet 

**Link :** https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=1236935374

**Observation :** Amount is seen properly on homepage after performing invite flow 

**Attachment :** invite_proper_amount.mp4](https://drive.google.com/file/d/1GXD1SLdTbqYgZ8oBh5g1IeW61oSEAaCn/view?usp=sharing)

**Verified on Devices :** OnePlus 7T(11.0), Redmi Note 8(9.0)

**CC** : @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in latest Android Internal build V:1.22.2 and updated the status in G sheet

**Gsheet Link** : https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=1236935374

**Verified on Devices :** Samsung Galaxy J5 Prime (8.0)

CC : @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in the latest Android Internal build V:1.22.2 & Test flight build V:1.22.2 and updated the status in the below Gsheet:

**Gsheet Link :** https://docs.google.com/spreadsheets/d/1PFIydvy_ZGZVDbhrWkt6fz8mRju1jzvlNMe1k8UDMlA/edit#gid=1236935374

**Verified on Devices :**  iPhone XR (14.6), Samsung Galaxy A21s (10.0)

CC : @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified the above issue in the latest Android Internal build V:1.22.3 & Test flight build V:1.22.3 and updated the status in test quality tool.

**Links**
**Android 12:** https://valora.testquality.com/project/12128/plan/23022/run/153500/result/2591356
**iOS 15:**  https://valora.testquality.com/project/12128/plan/23022/run/153500/result/2591216
**Devices:** Google Pixel 4a(12), iPhone 8(15.1)
CC: @gnardini 
Thanks..!!

**Pull request merged**
