### PR TITLE
feat: add username blocklist from Statsig dynamic config

### PR DESCRIPTION
**Pull request by anthonydaoud**
### Description

For an [onboarding experiment](https://www.notion.so/valora-inc/Onboarding-Name-Step-4b6ef3485ac64b0caeb87147887f68a5), we need to be able to generate random, fun usernames. This PR is a continuation of #2958 which obtains the adjective and noun blocklists from Statsig dynamic config. It does not yet use the blocklists in the `NameAndPicture` screen.

### Other changes

N/A

### Tested

N/A

### How others should test

N/A

### Related issues

- [ACT-435](https://linear.app/valora/issue/ACT-435/username-generator-helper-function)

### Backwards compatibility

N/A

### CODE REVIEW

**Comment by jh2oman** [comment]
I'm sorry for not realizing this in earlier discussions, but I think this would be a great opportunity to  try statsig Dynamic Config since this feature is already so closely tied to a statsig experiment. It should be substantially less code, just a function like this in NameAndPicture.tsx using [this dynamic config](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/dynamic_configs/usernameblocklist)

```js
const getBlockedUsernames = () => {
  try {
    const config = Statsig.getConfig('usernameBlockList')
    const blockedAdjectives = config.get('blockedAdjectives', [])
    const blockedNouns = config.get('blockedNouns', [])
    return { blockedAdjectives, blockedNouns}
  } catch (error) {
    Logger.warn('NameAndPicture', 'error getting Statsig blocked usernames', error)
  }
  return {
    blockedAdjectives: [],
    blockedNouns: []
  }
}
```

**Comment by anthonydaoud** [comment]
Just refactored it!

**Review by jh2oman — APPROVED** [review]
So clean 👏

**Review by jophish — APPROVED** [review]
Looks great - this seems like a good repeatable pattern

**Pull request merged**
