### PR TITLE
Update Valora Forum Link

### LINKED ISSUE #2388: "Oops this page is private" text is seen when user navigates to forum via help menu
**Frequency :** 100%

**Repro on build version:** Android Internal Release Build V:1.31.1 ,Android Playstore Build V:1.30.1,iOS Internal TestFlight Release Build V:1.31.1 ,iOS Appstore Build V:1.30.1
**Repro on device :** OnePlus 7t(11.0), Google Pixel 2XL(11.0), iPhone 13mini(15.1.1) , Google Pixel XL(10.0)

**Pre-condition:**
1] User must have installed the application
2] User must have completed onboarding process

**Repro Steps:**
1] tap on hamburger menu
2] Tap on help
3] Tap on forum and observe

**Bug :** Oops this page is private error is seen if user navigates to the forum page

**Expected Behavior :** User must be redirected to the correct URL of the forum'

**Impact :** user is not able to view the forum content on the page 

**Attachment :** [forum1.mp4](https://drive.google.com/file/d/1y5tU24UfFb5tP3ts_YvxKg7PnnX4J-zk/view?usp=sharing)

### PR DESCRIPTION
**Pull request by MuckT**
### Description

Updates the forum link with branding to https://forum.celo.org/c/valora/8

### Other changes

Updates the default link without branding to https://forum.celo.org

### Tested

Tested locally on iOS

### How others should test

1. Navigate to Help > Forum
2. Ensure Valora category loads.

### Related issues

- Fixes #2388

### Backwards compatibility

Yes

### CODE REVIEW

**Review by kathaypacific — APPROVED** [review]
💫

**Comment by MuckT** [comment]
@mergifyio refresh

**Comment by jeanregisser** [comment]
@mergifyio refresh

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above issue on Latest Android Internal Release Build & Test flight release build V1.32.0 and updated status in test rails.

**Test rail links:**
**iOS15:** https://valoraapp.testrail.io/index.php?/tests/view/33513
**iOS 14:** https://valoraapp.testrail.io/index.php?/tests/view/33498
**Android 10:** https://valoraapp.testrail.io/index.php?/tests/view/33528

**Devices:** iPhone 13 mini(15.1.1), iPhone 12(14.7.1), Google Pixel XL(10.0)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above issue on Latest Android Internal Release Build V1.32.0 and updated status in test rails.

**Test rail links:**
**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/33543

**Devices :** Google Pixel 2XL(11.0)

Thanks..!

**Pull request merged**
