### PR TITLE
Change the priority of incoming payment requests

### PR DESCRIPTION
**Pull request by gnardini**
### Description

Incoming payment requests require immediate action, so we are bumping them to show up first.

### Other changes

N/A

### Tested

Manually

### How others should test

Receive an invite request. Make sure it appears first in the notification list (only after the backup required notification)

### Related issues

- Fixes #

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
LGTM 👍

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android internal Build V:1.26.0 and updated status in Test rails

**Test rail link:**
**Android 8:**
https://valoraapp.testrail.io/index.php?/tests/view/9836&group_by=cases:section_id&group_order=asc&group_id=35

**Android 10:**
https://valoraapp.testrail.io/index.php?/tests/view/9962&group_by=cases:section_id&group_order=asc&group_id=35

**Devices:** Samsung Galaxy A8+(8.0), Samsung Galaxy M40(10.0)

**CC:** @gnardini 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android internal Build V:1.26.0 and updated status in Test rails

**Test rail link:**
**Android 11:**
https://valoraapp.testrail.io/index.php?/tests/view/9899&group_by=cases:section_id&group_order=asc&group_id=35

**iOS 14:**
https://valoraapp.testrail.io/index.php?/tests/view/9773&group_by=cases:section_id&group_order=asc&group_id=35

Observation : Invite CTA is seen on the first place incase there is no back up CTA or any other Major CTA eg : Dapps 

**Devices:** Google Pixel 2XL(11.0) , iPhone 12(14.7.1)

**CC:** @gnardini

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Test flight Release Build V1.26.0 and updated status in Test rails.

**Test rail link:**
**iOS 13:** https://valoraapp.testrail.io/index.php?/tests/view/10028&group_by=cases:section_id&group_order=asc&group_id=35

**Observation:** Invite CTA is not appearing at the first position after inviting a user, instead "Discover how to user..." cta appears at first position & if user has any pending payment request, it appears at first position. We have raised a [query](https://github.com/valora-inc/wallet/issues/2023) for the same.

**Devices:** iPhone 7(13.3)

**CC:** @gnardini 

Thanks..!!

**Comment by MuckT** [comment]
> How others should test
Receive an invite request...

@ValoraQA @gnardini  based on the code it seems that should read as payment request.

**Pull request merged**
