### PR TITLE
Fix WalletConnect sign/send now failing with Espresso hardfork nodes

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Fix WalletConnect sign/send now failing with Espresso hardfork nodes when it needs to call `estimateGas` when gas is not provided.

This fixes our E2E tests failing in the WalletConnect suite.

Note: I still need to asses whether existing Valora versions will actually be impacted by forno switching to version [1.5.0 of Geth](https://github.com/celo-org/celo-blockchain/releases/tag/v1.5.0). Initial thought is most dapps already set `gas` so this shouldn't be a real problem.

### Tested

- Updated unit tests
- E2E test works again

### How others should test

Dapps using WalletConnect can still sign/send transactions.

### Related issues

- Discussed on [Slack](https://valora-app.slack.com/archives/CL7BVQPHB/p1642105337052600)

### Backwards compatibility

Yes.

### CODE REVIEW

**Comment by jeanregisser** [comment]
Because of the vulnerability check issue, we'll need to manually merge this one (once all tests pass, except the expected vulnerability check failure) or https://github.com/valora-inc/wallet/pull/1774 to unblock other PRs.

**Review by lisaqyli — APPROVED** [review]

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android Internal build V:1.25.2 and Latest iOS testflight build V:1.25.2 and updated the status in test rails 

**Android 11**
https://valoraapp.testrail.io/index.php?/tests/view/7419&group_by=cases:section_id&group_order=asc&group_id=33

**iOS 14 :** 
https://valoraapp.testrail.io/index.php?/tests/view/7404&group_by=cases:section_id&group_order=asc&group_id=33

**Observation** Confirm pop up does not disappear even after approving the transaction from the wallet for sushi swap and we have raised a [bug](https://github.com/valora-inc/wallet/pull/1938) for it 

**Devices** : Google Pixel 2XL(11.0) , iPhone 12 (14.7.1)

**CC :** @jeanregisser 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android Internal build V:1.25.2 and updated the status in test rails

Android 8:

https://valoraapp.testrail.io/index.php?/tests/view/7497&group_by=cases:section_id&group_order=asc&group_id=33


**Observation** Confirm pop up does not disappear even after approving the transaction from the wallet for sushi swap and we have raised a [bug](https://github.com/valora-inc/wallet/pull/1938) for it

**Devices :** Samsung Galaxy J5 Prime(8.0.0)

**CC :** @jeanregisser

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android Internal build V:1.25.2 and updated the status in test rails

**Android 10:**

https://valoraapp.testrail.io/index.php?/tests/view/7512&group_by=cases:section_id&group_order=asc&group_id=33

**Observation**: Confirm pop up does not disappear even after approving the transaction from the wallet for sushi swap and we have raised a [bug](https://github.com/valora-inc/wallet/pull/1938) for it.

**Devices:** Samsung Galaxy M40 (10.0)

**CC** : @jeanregisser 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task on Latest Android Internal build V:1.25.2 & updated the status in test rails. 
**Test Rail link:**
**Android 10:** https://valoraapp.testrail.io/index.php?/tests/view/7542
**Bug:** [Bug1](https://github.com/valora-inc/wallet/issues/1889) 

**Devices:** Samsung Galaxy M40 (10.0), iPhone 7(13.3)

**CC** : @jeanregisser 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task on Latest Test flight release build V:1.25.2 & updated the status in test rails. 
Confirm transaction pop up in sushi dapp web page does not disappear even after approving the transaction from the Valora application for sushi swap.

**Test Rail link:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/7557

**Bug:**
[Bug1](https://github.com/valora-inc/wallet/issues/1889)
[Bug2](https://github.com/valora-inc/wallet/issues/1938) 

**Devices:** iPhone 13 mini (15.1.1)
CC: @jeanregisser  
Thanks..!!

**Pull request merged**
