### PR TITLE
Add Polish language support

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

As the title

### Other changes

N/A

### Tested

N/A

### How others should test

You should be able to select Polish for the app language

### Related issues

N/A

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
🇵🇱:tada:

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest iOS TestFlight Internal build V:.1.35.0 and updated status in Test rails

**Observation :**
- User is able to select polish language after opening the app for the first time from language page
- User is able to select Polish language via settings menu

**Test Rail links:**
**iOS 14:** https://valoraapp.testrail.io/index.php?/tests/view/47338

**Device :** iPhone 12(14.7.1)

**Cc :** @kathaypacific 

Thanks.!

**Comment by ValoraQA** [comment]
Hey @MuckT  we have verified the above task on Android Internal Release Build V:1.35.0 and updated status in Test rails

Observation : 
- User is able to select Polish language via settings menu
- For Android Platform: "Select Language" page does not appear on opening the app after fresh install.

**Test Rail links:**
Android 10: https://valoraapp.testrail.io/index.php?/tests/view/47400

**Device :** Samsung Galaxy M41(10.0)

**Cc :** @kathaypacific 
Thanks.!

**Comment by kathaypacific** [comment]
Hi @ValoraQA the "select language" page should only appear after a fresh install **if** the device language is not supported. if your device language is supported, you should see the onboarding screens right away. can you confirm what your device language is?

**Comment by ValoraQA** [comment]
Hey @kathaypacific, For few devices we are able to see "Select language" screen on fresh install and for few devices it is not displayed on fresh install & we have already raised a bug previously for the same.
- [Bug Link](https://github.com/valora-inc/wallet/issues/931)

**Pull request merged**
