### PR TITLE
Update auto-populated invite text for invite rewards users

### LINKED ISSUE #2291: Update autopopulated "send & invite" text
As an invitee in the invite rewards program, I should be invited into the program with specific details on who is inviting me, what I get for joining, and what I need to do to be eligible, so that I have more details to inform me about whether I want to participate.

See design here for the new copy: https://www.figma.com/file/DL6Huw867n1EZOVPJ2kNmp/Invite-Rewards?node-id=1150%3A25325

AC: 
* When a user is invited through the invite rewards program, they should see a text message that is specifically related to that program. 
* When a new user is sent money outside the context of the invite rewards program, the text message should not include details about the invite rewards program incentive. 

ENG:
- only eligible users should see this updated text

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

Details in #2291 

This PR adds a condition where if invite rewards are active for a user, after inviting a friend the auto populated text message content should mention the reward. For all other users, there should be no mention of this reward (i.e. the status quo)

### Other changes

N/A

### Tested

Manually + with unit tests

### How others should test

For users who are located in the US + when the invite rewards program is active (only true on Alfajores right now), the text they should see is "Hey! I’ve been using and enjoying Valora as a crypto wallet. If you download the app and connect your phone number, we’ll both get 5 cUSD. Use this link: [some invite link that links to the download page of the valora website]"

For all other users/when the invite rewards program is not active, there should be no mention of the 5 cUSD reward in the auto populated text message.

### Related issues

- Fixes #2291 

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
LGTM 👍

**Comment by ValoraQA** [comment]
Hey @MuckT below are the observations related to above PR
1] The text mentioned in the how other should test section is not seen when we perform send and invite flow
2] Even after connecting US VPN we are not able to see the text mentioned 

Note : We have checked in Alfajores build on both the platforms

Please guide us incase if there is some changes in the flow 

Attachment : [sendandinvite.mp4](https://drive.google.com/file/d/1wCys0EDHdq76hDg_m1w9zOMEbY76l4pi/view?usp=sharing)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest iOS Alfajores Build V1.32.0 & updated status in test rails.

**Observations:**

- 
“Confirmation error” popup appears when user tries to connect phone number after creating account, so user is not able to confirm the phone number. 

**New Bug :** https://github.com/valora-inc/wallet/issues/2467

**Test rail link:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/33518

**Devices:** iPhone 13 mini(15.1.1)
**cc:** @kathaypacific 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest iOS Test flight Alfa jores Build, Android Alfa jores Build V1.32.0 & updated status in test rails.

**Observation**

- Confirmation error is seen when user is connected to US VPN and tries to connect number
- Confirmation error is seen when user is not connected to VPN but tries to connect using US number

**New Bug :** [link](https://github.com/valora-inc/wallet/issues/2467)

**Test rail links:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/33518
**iOS 14:** https://valoraapp.testrail.io/index.php?/tests/view/33503

**Devices:** iPhone 13 mini(15.1.1), iPhone 12 (14.7.1)

**CC:** @kathaypacific

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest iOS Test flight Alfa jores Build V1.32.0 & updated status in test rails.

**Observation**

- Confirmation error is seen when user is connected to US VPN and tries to connect number
- Confirmation error is seen when user is not connected to VPN but tries to connect using US number
- 5cUSD is not getting credited in User B account when user downloads the application via invite link (Disabled from backend)

**New Bug :**[bug](https://github.com/valora-inc/wallet/issues/2467)

Test rail links:
Android 10: https://valoraapp.testrail.io/index.php?/tests/view/33533
Android 11: https://valoraapp.testrail.io/index.php?/tests/view/33548

CC: @kathaypacific

Thanks..!!

**Pull request merged**
