### PR TITLE
Fix known vulnerabilities

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

- Upgrade `@celo/utils` to fix vulnerability in `@umpirsky/country-list`: https://github.com/advisories/GHSA-hj79-42mx-m4gr
  - The upgraded `@celo/utils` caused a new parsing error with hermes as it [doesn't support named capture groups in RegEx](https://github.com/facebook/hermes/issues/696). It was solved by adding `@babel/plugin-transform-named-capturing-groups-regex` to our babel transforms.
- Upgrade `shell-quote` to fix vulnerability: https://github.com/advisories/GHSA-g4rg-993r-mgx7

### Other changes

N/A

### Tested

The app + phone verification should work as expected

### How others should test

Please test the phone verification and confirm that it works as expected (there should be no change as a result of this PR)

### Related issues

Discussed on [Slack](https://valora-app.slack.com/archives/CL7BVQPHB/p1655807207073809).

### Backwards compatibility

Yes

### CODE REVIEW

**Comment by kathaypacific** [comment]
Looks great, thank you Jean!!!! 🚀

**Comment by ValoraQA** [comment]
Hey @MuckT we will check the above PR while performing BVT and Regression testing and update in the comment accordingly if any issues is faced

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above PR while performing BVT's and here are the below links for the same

**Test Rail links:**
**Android 10 :** https://valoraapp.testrail.io/index.php?/runs/view/158&group_by=cases:section_id&group_order=asc
**Android 12:** https://valoraapp.testrail.io/index.php?/runs/view/159&group_by=cases:section_id&group_order=asc
**iOS 14:** https://valoraapp.testrail.io/index.php?/runs/view/161&group_by=cases:section_id&group_order=asc
**iOS 15 :** https://valoraapp.testrail.io/index.php?/runs/view/160&group_by=cases:section_id&group_order=asc

**Devices :** iPhone 13 mini (15.1.1), iPhone 12(14.7.1), Google Pixel 4a(12.0), Google Pixel XL (10.0)

**CC**: @kathaypacific 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above PR while performing Regression testing and here are the below links for the same

**Test Rail links:**
**Android 12:** https://valoraapp.testrail.io/index.php?/runs/view/167&group_by=cases:section_id&group_order=asc
**iOS 15 :** https://valoraapp.testrail.io/index.php?/runs/view/166&group_by=cases:section_id&group_order=asc

**Devices :** iPhone 13 mini (15.1.1), Google Pixel 4a(12.0)]

**CC:** @kathaypacific 

Thanks..!!

**Pull request merged**
