### PR TITLE
Change copy of rewards screen

### LINKED ISSUE #998: Update the savings T&C in the app
The T&C for savings program in the app and at the celo.org should reflect the next changes to the program:
- now the reward will be distributed for both holding cUSD and cEUR balances;
- the cap is 1,000 for each currency (in total, users may receive the reward for up to 1,000 cUSD and 1,000 cEUR at the same time;
- going forward we are also introducing the minimum of 0,01 cent to be eligible for receiving the reward.

The APY value listed in the app should be dynamic value and change when we change the APY from the backend, so we don't have to update the app to make this small change.

### PR DESCRIPTION
**Pull request by gnardini**
### Description

Just copy changes to the rewards screen

Screen Shot 2021-09-02 at 14 25 10

### Other changes

N/A

### Tested

Manually

### How others should test

Go to the rewards screen and make sure you see the right copy.

### Related issues

- Fixes #998

### Backwards compatibility

N/A

### CODE REVIEW

**Review by cajubelt — APPROVED** [review]

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Gsuite.

**Verified On Devices:** Samsung Galaxy J5 Prime (8.0), Samsung Galaxy M01 Core (10.0)

**GSuite:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1206218866&range=J3

**Query:** 
- Also we have observed that, below "Earn without commitments" section we are able to see  "Earning is stress free: Connect your phone number to start earning" text but in attached snapshot we are able to see "Earning is stress free: Add cUSD or cEUR to your account and start earning on your balances" text. So is it expected or we need to raise ticket for same?
**Attachment:** [EarnRewardDescriptionSomewhatDifferenceThanSnapshot](https://drive.google.com/file/d/1zyA23NbRHjM_fami6_Y4TYfzahg3lQYI/view?usp=sharing)

 CC: @gnardini

**Comment by gnardini** [comment]
Oh, the copy needs to change depending on wether the user connected their phone number or not. 

Yes, please do raise a P2 ticket, thanks!

**Comment by ValoraQA** [comment]
Hey @gnardini thanx for more information. Here are our observation for both cases:

- [ ]  For verified number we are able to see "Earning is stress free: Add cUSD or cEUR to your account and start earning on your balances" text & 
- [ ] For unverified number able to see "Earning is stress free: Add cUSD or cEUR to your account and start earning on your balances" text on "A new way to earn" page.
**Verified On Devices:** Samsung Galaxy J5 Prime (8.0), Samsung Galaxy M01 Core (10.0)
**Attachment:** 
[AbleToSeeExpectedTextForVerifiedNumber](https://drive.google.com/file/d/1Fqf-v166R0Rmc6zJygN1tAfkzNOqPexP/view?usp=sharing)
[AbleToSeeExpectedTextForNonVerifiedNumber](https://drive.google.com/file/d/1zyA23NbRHjM_fami6_Y4TYfzahg3lQYI/view)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @gnardini,  We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Gsuite.

**Sheet link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=1206218866

**Devices:** iPhone 12 (14.7.1), Redmi Note 8 (10.0)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R86](https://valora.testquality.com/project/12128/testcase/299599/requirement/11857).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:
Android (9.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485119

**Verified On Devices:** Redmi Note 8 (9.0) 

CC: @gnardini

**Pull request merged**
