### PR TITLE
Make MAX button include fee

### LINKED ISSUE #1585: Fix the logic behind the MAX button
If the token the user is using to pay for fees is the same as the token the user wants to send and the user presses the MAX button, then sending doesn't work.

This is the relevant section of the code: https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/send/SendAmount/index.tsx#L105

There's a `useFeeCurrency` hook in `src/fees/hooks` we can use to know which token will be used to pay for fees.

One note is that fee estimation is paid in the same screen a bit below, here: https://github.com/valora-inc/wallet/blob/main/packages/mobile/src/send/SendAmount/index.tsx#L176
so the user might press the MAX button before the fee is estimated. Not sure what to do in that case, we can maybe use a default value for the fee? Or update the amount after fee estimation finishes, although that would add quite some complexity. A decision to be made.

### PR DESCRIPTION
**Pull request by gnardini**
### Description

When pressing the MAX button we now substract the fee from the total balance.

### Other changes

- Removed the tilde symbol
- Changed the way to calculate the fee currency (it was comparing to zero instead of a min value to pay for the fee).
- Added a small padding to the max and swap buttons.
- Fixed a bug when sending related to the gas variable (not sure how/if it was working??)

### Tested

Manually and added unit test

### How others should test

Press the MAX button and see that sending works.

### Related issues

- Fixes #1585

### Backwards compatibility

N/A

### CODE REVIEW

**Review by MuckT — CHANGES_REQUESTED** [review]
@gnardini I have been able to confirm that the tilde was removed, padding was added and fee's are included when sending tokens.

I am seeing reverted transactions when the wallet has only one coin and they attempt to send the max amount in local currencies e.g. the wallet has 1 cUSD when I tap max the input value reflects $1 instead of .99 so it appears that the fee's cannot be covered.

Error sending max local currency with one token in wallet
```
Possible Unhandled Promise Rejection (id: 1):
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xb1bc717b6ea13089997a0ed8eae6a7a975d39e56402ef60a9edc90420da8286d",
  "blockNumber": 8951229,
  "contractAddress": null,
  "cumulativeGasUsed": 85936,
  "from": "0x43b53c887df96d5046999308d245788f0336079e",
  "gasUsed": 85936,
  "logsBloom": "0x00000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000008000000002000000000000000000008000000000000000000000000000000000000000000000000000000000000000010000000001000000800040000000000000000000000400000000000000000000400000000000000000000040000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000008000000000000000000000100000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x874069fa1eb16d44d622f2e0ca25eea172369bc1",
  "transactionHash": "0xdf5fb675ccbd0e7801b597766d53c98cc3359420babd<…>
```

Also another minor nit is after swapping it appears there is a leading zero.

https://user-images.githubusercontent.com/26950305/146982357-f39375cc-4e7e-480d-9044-3e5d5eabe9d2.mov

**Comment by gnardini** [comment]
It was a rounding issue, rounding down now when pressing the MAX button. Sometimes the value will defer with the balance by 1 cent, but I guess it's fine for now until we take a closer look at rounding throughout the app.

**Comment by MuckT** [comment]
@gnardini I am no longer seeing reverted transactions. I do still see the issue in the video where 0 is prepended after swapping. Is this something you want to fix in this PR?

**Comment by gnardini** [comment]
Yes, just pushed a fix, thanks for testing the feature!

**Review by MuckT — APPROVED** [review]

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this issue using Latest Android Alfajores build V1.24.0 , Test flight Alfajores Build V1.24.0 & added our results in below sheet.

**Sheet Link:** https://docs.google.com/spreadsheets/d/1LcYXmQcuLTBIHZrzUjoYaUvnzisq2ReRvxVwmn-xGEA/edit#gid=88659801

**New Bug:**
1. [Link 1](https://github.com/valora-inc/wallet/issues/1725)
2. [Link 2](https://github.com/valora-inc/wallet/issues/1727)
**Devices:** iPhone 13 mini (15.1.1), Google Pixel 2XL (11.0)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this task using Latest Android Internal build and Test flight build V1.24.1 and added the observation in below sheet.

**Sheet Link**:
https://docs.google.com/spreadsheets/d/15nGo3iJAEVJ76wHae9PvYuWI7S2bovKAQPX_edtwPEI/edit#gid=2039480032

**Observation**: We are not able to see exchange button for Test Token and we have raised [query](https://drive.google.com/file/d/1qRh9U6HP9Ws1XynKE5lRVOh-7fV7MFA3/view?usp=sharing) for the same.

**Devices**  : Galaxy M40 (10.0), Google Pixel 2XL (11.0), iPhone 12 (14.7.1), iPhone 13 mini (15.1.1)

CC: @gnardini
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this task using Latest Android Internal release build and added the observation in below sheet.

**Sheet Link**:
https://docs.google.com/spreadsheets/d/15nGo3iJAEVJ76wHae9PvYuWI7S2bovKAQPX_edtwPEI/edit#gid=1988587388

**Observation**: We are not able to see exchange button for Test Token and we have raised [query](https://github.com/valora-inc/wallet/issues/1794) for the same.

**Bug Link** : [1772](https://github.com/valora-inc/wallet/issues/1772)

**Devices** : Samsung Galaxy A8+(8.0)

CC: @gnardini
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified this task using Latest Test flight release build and added the observation in below sheet.

**Sheet Link**:
https://docs.google.com/spreadsheets/d/15nGo3iJAEVJ76wHae9PvYuWI7S2bovKAQPX_edtwPEI/edit#gid=1988587388

**Observation**: We are not able to see exchange button for Test Token and we have raised [query](https://github.com/valora-inc/wallet/issues/1794) for the same.

**Bug Link** : [1772](https://github.com/valora-inc/wallet/issues/1772)

**Devices** : iPhone 7(13.3)

CC: @gnardini
Thanks..!!

**Pull request merged**
