### PR TITLE
fix bug with skip verification

### PR DESCRIPTION
**Pull request by jh2oman**
### Description

I fixed part of this bug in https://github.com/valora-inc/wallet/pull/2259 but did not notice that i needed to also fix for the case when biometrics was enabled.

### Tested

Tested skip verification manually with biometrics enabled.

### How others should test

See that https://github.com/valora-inc/wallet/issues/2183 does not repro.

### Related issues

- Fixes https://github.com/valora-inc/wallet/issues/2183

### CODE REVIEW

**Review by cajubelt — APPROVED** [review]
nice find

**Review by lisaqyli — APPROVED** [review]

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Test flight Alfajores build V1.30.1 & updated status in test rails.

**Observations:**

- If we go to rewards page and click on connect number then also phone number verification page is seen. 
**Reference link:** [link](https://github.com/valora-inc/wallet/issues/2183#issuecomment-1082894933)

**Test rail links:**
**iOS15:** https://valoraapp.testrail.io/index.php?/tests/view/27213

**Devices:** iPhone 13 mini(15.1.1)

**CC:** @jh2oman 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Android Alfa jores Build V:1.30.1 & updated status in test rails.

- User is navigated to home screen when user kills & relaunches the application after both creating new account and restoring account.

**Test rail links:**
**Android 9:** https://valoraapp.testrail.io/index.php?/tests/view/27244

**Devices:** Redmi Note 5 Pro (9.0)
**CC:** @jh2oman 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest iOS Alfa jores Build V:1.30.1 & updated status in test rails.

Observation : User is navigated to home screen when user kills & relaunches the application after both creating new account and restoring account.
Test rail links:
iOS 14: https://valoraapp.testrail.io/index.php?/tests/view/27306&group_by=cases:section_id&group_order=asc&group_id=43

Devices: iPhone 12(14.7.1)
CC: @jh2oman
Thanks..!!

**Pull request merged**
