### PR TITLE
Adding CEUR balance to the Bidali screen

### PR DESCRIPTION
**Pull request by corymsmith**
### Description

Adds the CEUR balance to the BidaliScreen

### Tested

I couldn't run the tests for some reason due to tons of these errors: 
`Cannot find module '@celo/komencikit/lib/kit' from 'src/escrow/saga.ts'`

### How others should test

Until we (Bidali) fully add support on our side we can't fully test the flow end to end.

### Backwards compatibility

This only adds the balance to the `window.valora` object so that users can spend their cEUR once its all set up in our API / backend and so that we can show a "Not enough balance" error if the user does not have sufficient funds to make a purchase.

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
This is awesome!!
Thanks so much and really appreciate the updated tests 🚀

**Review by tarikbellamine — APPROVED** [review]
Awesome...thanks!

**Comment by corymsmith** [comment]
No worries! Happy to help out, keep me posted in Slack when it gets fully rolled out.

**Comment by jeanregisser** [comment]
@corymsmith could you merge latest `main` into your branch? 🙏 
We're requiring branch to be up-to-date for merging and we don't have access to do this ourselves from your PR.

**Comment by corymsmith** [comment]
@jeanregisser Just merged it in now. I also the updates done on our side so if you want to test on Alfajores / our `staging` env then you can now.

**Comment by MuckT** [comment]
@corymsmith would you merge in main to your branch again? There have been changes to main and this branch is no longer up to date with main so we are unable to merge. Thanks in advance!

**Comment by corymsmith** [comment]
@MuckT Done!

**Comment by jeanregisser** [comment]
Erf, looks like we keep missing each other on this.
@corymsmith could you update your branch one more time and directly ping me on Slack afterwards? 
Thanks for your patience 🙏

**Comment by ValoraQA** [comment]
We have verified this using another [PR](https://github.com/valora-inc/wallet/issues/999) using Latest testflight build V1.19.0 & updated the results in test quality tool.

Note: We have skipped for Android as we do not have the latest alphajores build V1.19.0, the latest alphajores build for android is V1.18.3

iOS (12.5.4, 13.7, 14.7.1)
https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485148
https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485154
https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485160

Devices:  iPhone 12 (14.7.1) , iPhone 6+ (12.5.4),iPhone SE(13.6.1)
Thanks..!!

**Pull request merged**
