### PR TITLE
Token / Asset Display Fix

### LINKED ISSUE #2294: Assets display cannot handle large text or long token names
### Current behavior
Long token names or accessibility fonts break the layout of assets under total balance.

### Desired behavior
Items should be display with large font and long token names with a two column layout utilizing ellipses.

### Steps to Reproduce
1. Set font size to large or have an assets with a long token name e.g. mCUSD.
2. From the home screen tap 'View Assets'.
3. Observe page layout

### Versions

All versions since [1.22.0](https://github.com/valora-inc/wallet/releases/tag/valora-v1.22.0).

### PR DESCRIPTION
**Pull request by MuckT**
### Description

Adjust the layout for tokens in the bottom sheet and assets page to accommodate long token names.

### Other changes

Snapshots updated.

### Tested

Tested locally on iOS and Android.

### How others should test

- Observe the token bottom sheet with a token such as mCUSD in the wallet.
- Observe the Asset list (Transaction feed > View Assets) with a token such as mCUSD in the wallet.

### Related issues

- Fixes #2294, #2295

### Backwards compatibility

Yes

#### Token Bottom Sheet

<div>
  
  
</div>

#### Assets Screen

<div>
  
  
</div>

### CODE REVIEW

**Review by gnardini — COMMENTED** [review]
This looks good to me, but would you mind adding a screenshot to the PR description since this is a visual change?

**Review by gnardini — APPROVED** [review]
🙌

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above task on Latest Android internal release build , Test flight release build V1.31.0 and updated status in test rails.

**Observation :** Small alignment is observed when the display size and font size is changed to MAX for both Android and iOS Platform

**Test rail links:**
iOS15: https://valoraapp.testrail.io/index.php?/tests/view/30616
iOS 14: https://valoraapp.testrail.io/index.php?/tests/view/30680
Android 9: https://valoraapp.testrail.io/index.php?/tests/view/30647
Android 11: https://valoraapp.testrail.io/index.php?/tests/view/30709

Devices: iPhone 13 mini(15.1.1), iPhone 12(14.7.1), Redmi Note 5 pro (9.0), Google Pixel 2XL(11.0)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified above task on Latest Android internal release build , Test flight release build V1.31.0 and updated status in test rails.

**Observation :** Small alignment is observed when the display size and font size is changed to MAX for both Android and iOS Platform
Attachment : [iOS](https://drive.google.com/file/d/1H883bRTx6-AXGtJAgmJJocQ1IVu5jykc/view?usp=sharing) , [Android](https://drive.google.com/file/d/1ys96GJ67drh4Hl7wcBVhEb1Xxjh1IFBN/view?usp=sharing)

**Test rail links:**
iOS15: https://valoraapp.testrail.io/index.php?/tests/view/30616
iOS 14: https://valoraapp.testrail.io/index.php?/tests/view/30680
Android 9: https://valoraapp.testrail.io/index.php?/tests/view/30647
Android 11: https://valoraapp.testrail.io/index.php?/tests/view/30709

Devices: iPhone 13 mini(15.1.1), iPhone 12(14.7.1), Redmi Note 5 pro (9.0), Google Pixel 2XL(11.0)

Thanks..!!

**Pull request merged**
