### PR TITLE
Dapp Marketplace internationalization

### PR DESCRIPTION
**Pull request by dievazqu**
### Description

Dapp Marketplace supports non-english languages

### Tested

Manually in a iOS emulator

### How others should test

In other to be able to use this code, you should set `dappsExplorerEnabled` as `true` and `dappListApiUrl` to `https://us-central1-celo-mobile-alfajores.cloudfunctions.net/dappList`

### After merge 
After merging we should set the `dappListApiUrl` remote config param to `https://us-central1-celo-mobile-alfajores.cloudfunctions.net/dappList` in alfajores.

### Screenshot
Simulator Screen Shot - iPhone 12 - 2022-01-19 at 16 36 37

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
Niceee 🔥

**Comment by MuckT** [comment]
@dievazqu I thin we still need the `dappsExplorerEnabled` flag in the mainnet remote config.

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task in latest Android Alfajores Build and Latest iOS Alfajores Build V:1.25.1 and updated status in test rails

**iOS 14**
https://valoraapp.testrail.io/index.php?/tests/view/4338&group_by=cases:section_id&group_order=asc&group_id=30

**Android 11**
https://valoraapp.testrail.io/index.php?/tests/view/4268&group_by=cases:section_id&group_order=asc&group_id=30

**Observation** We are able to view dapps in the hamburger menu and also we are able to access it 

**Devices**  : Google Pixel 2XL(11.0), iPhone 12(14.7.1)

**CC:** @dievazqu 

Thanks.!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task in latest Latest iOS Alfajores Build V:1.25.2 and updated status in test rails

**Test rail link:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/4457

Observation We are able to view dapps in the hamburger menu and also we are able to access it

**Devices:** iPhone 13 mini (15.1.1)
CC: @dievazqu 
Thanks.!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task in Latest Android Alfajores Build V:1.25.2 and updated status in test rails

**Test rail link:**
**Android 10:**https://valoraapp.testrail.io/index.php?/tests/view/7075&group_by=cases:section_id&group_order=asc&group_id=30

**Observation**: We are able to view dapps in the hamburger menu and also we are able to access it

**Devices:** Samsung Galaxy M40(10.0)

**CC:** @dievazqu 
Thanks.!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task in Latest Android Alfajores Build V:1.25.2 and updated status in test rails

Test rail link:
Android 8: 
https://valoraapp.testrail.io/index.php?/tests/view/7138&group_by=cases:section_id&group_order=asc&group_id=30

**Observation**: We are able to view dapps in the hamburger menu and also we are able to access it

**Devices:** Samsung Galaxy M40(10.0)

**CC:** @dievazqu
Thanks.!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above task in Latest Android Alfajores Build V:1.25.2 and updated status in test rails.

**Test rail link:**
**Android 9:** https://valoraapp.testrail.io/index.php?/tests/view/7462

**Observation**: We are able to view dapps in the hamburger menu and also we are able to access it
**Devices:** Redmi Note 5 Pro (9.0)
cc: @dievazqu
Thanks.!!

**Pull request merged**
