### PR TITLE
A small fix for 'Cancel' Text button alignment in header

### PR DESCRIPTION
**Pull request by MuckT**
### Description

A small PR to fix the alignment of the cancel button when it is shown as text.

<details><summary>Recovery Phrase</summary>

Simulator Screen Shot - iPhone 11 - 2021-09-08 at 09 09 51

Simulator Screen Shot - iPhone 11 - 2021-09-08 at 09 06 36

</details>

<details><summary>Edit Profile</summary>

Simulator Screen Shot - iPhone 11 - 2021-09-08 at 09 10 03

Simulator Screen Shot - iPhone 11 - 2021-09-08 at 09 06 52

</details>

### Tested

Tested locally on iOS and Android

### How others should test

- Complete onboarding with a new account and navigate to setup account key complete the process until the account key is displayed - The cancel button should be correctly aligned to the right regardless of text sizing
- Using an existing account with a balance and default text sizing navigate to buy or sell CELO -> On the review screen observe the cancel button alignment - Should be consistent.

### Backwards compatibility

This PR is backwards compatible.

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
LGTM 👍 
Would be great to see screenshots added to the PR.

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified issue on Android internal build & Testflight Build V:1.19.0 and updated status in below sheet 

**GSuite sheeet link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=283267830

**Verified On Devices:** OnePlus 7T (11.0), Iphone 6+ (12.5.4), Samsung Galaxy J5 Prime (8.0), Samsung Galaxy M01 Core (10.0)
**New Bug:**
- We have observed that "<" arrow instead of "cancel" button for both Buy/Sell CELO & Buy/Sell CELO total screen

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R96](https://valora.testquality.com/project/12128/testcase/299810/requirement/11867).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:**
**iOS (13.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485065

**Verified On Devices:** iPhone SE (13.6.1)
CC : @jeanregisser

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:
Android (9.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485129

**Verified On Devices:** Redmi Note 8 (9.0)

**Pull request merged**
