### PR TITLE
Update invite link

### LINKED ISSUE #1165: Change dynamic link in invite SMS
AC:
- [ ] The link sent in the SMS Valora pre-populates for users inviting friends should be `https://vlra.app/invite`

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Updated the invite link to be https://www.vlra.app/invite

### Other changes
Removed the dynamic link generation as it appears to no longer be needed

### Tested
Manually

### How others should test
Ensure the invite link sent in the SMS links to the relevant app store

### Related issues
- Fixes #1165

### Backwards compatibility
Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
The deleted code was very old and used when we created the temporarily funded address to invite with a code I think, so definitely makes sense to delete it :D

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this task using Latest Android Internal build V1.20.2 & updated the status in Test Quality Tool.
Test Quality Tool Link:

**Android(10):**
Case1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516287
Case2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516288

**iOS (14):**
Case1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516351
Case2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516352

**Devices:** Redmi Note 8(10.0), iPhone 12 (14.7.1)

**CC:** @tarikbellamine

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this task using Latest Android Internal build V1.20.2 updated the status in Test Quality Tool.
**Test Quality Tool Link:**
- https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516304

**Verified On Devices:** Redmi Note  8 (9.0)

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this task using Latest Test flight Build V1.20.2 & updated the status in Test Quality Tool.

**Test Quality Tool Link:**

iOS(15.0):
Case 1: 
Case 2: 
Devices: iPhone 12 (14.7.1)

**Pull request merged**
