### PR TITLE
Update known vulnerabilities - simple-plist and moment projects

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

Example of new vulnerability alerts https://github.com/valora-inc/wallet/runs/5970939718?check_suite_focus=true

Resolve versions of simple-plist and moment to unblock CI

### Other changes

N/A

### Tested

N/A

### How others should test

N/A

### Related issues

N/A

### Backwards compatibility

Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
Thanks! 😄

**Comment by MuckT** [comment]
@kathaypacific it looks like this adds [moment](https://www.npmjs.com/package/moment) to the `package.json`, but I see we are only using [moment-timezone](https://www.npmjs.com/package/moment-timezone). Is this expected?

**Comment by MuckT** [comment]
@kathaypacific I merged this into the e2e refactor branch to unblock CI in https://github.com/valora-inc/wallet/pull/2277/commits/610afd8d441b269167fa5553fd2d3260cad3b812.

**Comment by ValoraQA** [comment]
Hey @MuckT as N/A is mentioned in how to test hence we are skipping this PR

**Pull request merged**
