### PR TITLE
Remove last tslint vestiges

### PR DESCRIPTION
**Pull request by silasbw**
closes https://github.com/valora-inc/wallet/issues/784

### CODE REVIEW

**Review by tarikbellamine — COMMENTED** [review]
I'm seeing this error:

```
{
	"resource": "/Users/tarik/celo/wallet/packages/mobile/.eslintrc.js",
	"owner": "eslint",
	"severity": 8,
	"message": "Parsing error: \"parserOptions.project\" has been set for @typescript-eslint/parser.\nThe file does not match your project config: .eslintrc.js.\nThe file must be included in at least one of the projects provided.",
	"source": "eslint",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

Separately, can we also remove the `tsconfig-paths` package? I don't know what it's for but doesn't appear to be imported anywhere.

**Comment by silasbw** [comment]
What produces that error?

**Comment by silasbw** [comment]
...and is it present on `main`?

**Comment by silasbw** [comment]
FYI, https://github.com/valora-inc/wallet/pull/1224 aims to address the issue @tarikbellamine calls out.

**Review by tarikbellamine — APPROVED** [review]

**Pull request merged**
