### PR TITLE
Use valora terms of service link

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This updates the terms of service link shown during onboarding.

See https://valora-app.slack.com/archives/CL7BVQPHB/p1630331670018800

This is cherry-picked from the [1.18.1 release branch](https://github.com/valora-inc/wallet/tree/release/wallet/1.18.1).

### CODE REVIEW

**Review by noisypigeon — APPROVED** [review]
LGTM!

**Review by gnardini — APPROVED** [review]

**Comment by ValoraQA** [comment]
Hey @jeanregisser  We have verified this issue using latest Test flight build V 1.19.0, Android internal build V1.19.0 & updated status in Gsuite.

**GSuite Link:** https://docs.google.com/spreadsheets/d/1bWi6smdTMClreG96sGjYxb2lee9Ja6eT4-Lm7eXm1gM/edit#gid=147147057

**Verified On Devices:** Redmi note 8 (10.0), iPhone 12 (14.7.1)

CC: @tarikbellamine

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R88](https://valora.testquality.com/project/12128/testcase/299606/requirement/11859).

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Test flight build V 1.19.0 and Android internal build V1.19.0 & updated status in Test Quality Tool

**Test Quality Tool link:
Android (9.0):**
- https://valora.testquality.com/project/12128/plan/21816/run/150277/result/2485121

**Verified On Devices:** Redmi Note 8 (9.0)

CC: @jeanregisser

**Comment by ValoraQA** [comment]
Hey @MuckT Can you please take a look for this query ?
**Query:** 

- [ ] We have observed that user is able to see extra information for "Data and Privacy" header as compared to snapshot attached in ticket.  Can you please let us know is it expected or we need to raise a ticket for same ?
**Attachment:** [T&CData&PrivacyInfoExtraThanSnapAttached.png](https://drive.google.com/file/d/1gOjiCsVV-zwPNGN3Ehw3EanOsPs2gYEH/view?usp=sharing)

**Pull request merged**
