### PR TITLE
Bump version to 1.29.0

### PR DESCRIPTION
**Pull request by gnardini**
### Description

As part of the release process, bump the app version to 1.29

### Other changes

N/A

### Tested

N/A

### How others should test

No need

### Related issues

N/A

### Backwards compatibility

N/A

### CODE REVIEW

**Comment by kathaypacific** [comment]
Hey Gonza sorry could we put this on hold? i'm hoping that the automated job for this i just merged will kick off after you create the 1.28 tag! https://github.com/valora-inc/wallet/pull/2098 :D

**Comment by kathaypacific** [comment]
Ah darn, i made a mistake in the auto version bump script so it didn't run correctly. So approving this one, thanks for this!!

**Review by kathaypacific — APPROVED** [review]

**Comment by kathaypacific** [comment]
@mergifyio refresh

**Comment by ValoraQA** [comment]
Hey @MuckT JFYI: We are skipping this task as in "How others should test" section it is mentioned N/A.
Cc: @gnardini 

Thanks !!

**Pull request merged**
