### PR TITLE
Merge all translation files into a single file

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

Combine all translation files to one.
- remove translations from translated languages, wait for Crowdin PR to replenish those
- rename some (very few) translation keys that were duplicated across files
- remove some keys that were not being used (didn't actively try to do this, but when dealing with duplicate keys if i found something wasn't used in the mobile package then i removed them)
- remove index.ts files from locale folders
- still load the translations files in the same way, so that only the required language(s) is/are loaded in memory

### Other changes

N/A

### Tested

Clicked around the app (in english) and see no translation keys , and see correct looking copy

### How others should test

Same as above

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Review by silasbw — APPROVED** [review]
rubber stamp

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing 
**Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682
**FYI:** We have checked all applications in the English language & updated the status here for BVT testing.
**Verified On Devices:**  iPhone SE(14.6), Google Pixel 2XL (11.0)
Can you please let us know if we need to test any other thing here ?
Thanks..!!
CC: @kathaypacific

**Comment by kathaypacific** [comment]
> Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing **Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682 **FYI:** We have checked all applications in the English language & updated the status here for BVT testing. **Verified On Devices:** iPhone SE(14.6), Google Pixel 2XL (11.0) Can you please let us know if we need to test any other thing here ? Thanks..!! CC: @kathaypacific

Hi team, this change was more for technical purposes - it is expected that the app behaviour/text displayed in all screens of the app is not affected :) nothing else needs to be tested aside from normal smoke/regression testing.

**Comment by ValoraQA** [comment]
> > Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing **Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682 **FYI:** We have checked all applications in the English language & updated the status here for BVT testing. **Verified On Devices:** iPhone SE(14.6), Google Pixel 2XL (11.0) Can you please let us know if we need to test any other thing here ? Thanks..!! CC: @kathaypacific
> 
> Hi team, this change was more for technical purposes - it is expected that the app behaviour/text displayed in all screens of the app is not affected :) nothing else needs to be tested aside from normal smoke/regression testing.

Thank you @kathaypacific for confirmation:)

**Comment by ValoraQA** [comment]
> > Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing **Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682 **FYI:** We have checked all applications in the English language & updated the status here for BVT testing. **Verified On Devices:** iPhone SE(14.6), Google Pixel 2XL (11.0) Can you please let us know if we need to test any other thing here ? Thanks..!! CC: @kathaypacific
> 
> Hi team, this change was more for technical purposes - it is expected that the app behaviour/text displayed in all screens of the app is not affected :) nothing else needs to be tested aside from normal smoke/regression testing.

Hey, @kathaypacific We have completed [BVT]( https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682) in the test quality tool. Can you please let us know if we need to perform regression testing on v1.22.2?
CC: @MuckT

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing
**Test Quality Tool**: https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586686
**FYI:** We have checked all applications in the English language & updated the status here for BVT testing.
**Verified On Devices:** Samsung Galaxy J5 Prime (8.0)
Thanks..!!
CC: @kathaypacific

**Pull request merged**
