### PR TITLE
Remove flex that was hiding next button on older android devices

### PR DESCRIPTION
**Pull request by MuckT**
### Description

On older Android Devices during onboard the next button could become hidden -  scrolling up out of view. Changing `flex: 1` to `flexGrow: 1` in the scrollview container appears to solve this issue.

### Other changes
- Test Snapshots updated

### Tested

Tested locally on An Android 5.1 emulator.

### How others should test

Perquisites: In release mode on an Android device 5.0 - 6.0 device with a small screen.

1. Attempt to complete the new account or restore onboarding flow. 

2. After filling out your name attempt to tap the next button - it should still be visible.

Notes on running in release mode - [Slack](https://valora-app.slack.com/archives/C025V1D6F3J/p1645005818597379?thread_ts=1644957084.379739&cid=C025V1D6F3J).

### Related issues

N/A

### Backwards compatibility

Yes

### CODE REVIEW

**Comment by kathaypacific** [comment]
hey @MuckT i'm not sure i understand the problem so not sure what to suggest, but removing the styles in this PR doesn't for me? since we're applying the background color on this container, once you stop forcing the container to take up the full flex space then the background color doesn't extend to the whole screen

Screenshot 2022-03-25 at 09 46 53

**Comment by MuckT** [comment]
@kathaypacific Here's the issue I am seeing on Android 5.1

https://user-images.githubusercontent.com/26950305/160144973-74c74c70-0ef3-46ec-9cef-0cfd47773ebe.mov

**Review by kathaypacific — APPROVED** [review]
Thanks! I couldn't see this issue myself (unfortunately the oldest system image i can find for arm64 is 7.0) but would be curious if this also happens for the phone number verification? seems like the flex container there is just using `flex:1` as well

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Android Internal Release Build V1.29.2 & updated status in test rails.

- User is able to install the app and app is not crashing.

**Device**: Lg K7i(6.0)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Android Internal Release Build V1.29.2 & observed that User is able to install the app and app is not crashing.
Link : https://valoraapp.testrail.io/index.php?/runs/view/94&group_by=cases:section_id&group_order=asc
Device: Samsung Galaxy A3(5.0.2)
Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Android Internal Release Build V1.30.1 & observed that User is able to install the app and app is not crashing.

Link : https://valoraapp.testrail.io/index.php?/tests/view/27288&group_by=cases:section_id&group_order=asc&group_id=43
Device: Samsung Galaxy A3(5.0.2) , LG K7i(6.0)
Thanks..!

**Pull request merged**
