### PR TITLE
test(e2e): use iPhone SE for iOS detox test device

### PR DESCRIPTION
**Pull request by MuckT**
### Description

Switches our iOS E2E tests to use a smaller device following up the incident that resulted in #3536. 

### Test plan

Tested in CI.

### Related issues

Fixes RET-665

### Backwards compatibility

Yes

### CODE REVIEW

**Comment by MuckT** [comment]
@kathaypacific it looks like this might have uncovered an issue with the dapps bottom sheet.
Screen Shot 2023-03-16 at 7 45 00 PM

**Review by jeanregisser — APPROVED** [review]
Great idea!! 🚀

**Comment by jeanregisser** [comment]
> @kathaypacific it looks like we'll need to scroll on some of the wallet connect tests. Screen Shot 2023-03-16 at 7 45 00 PM

Ah weird, this bottom sheet is supposed to measure itself and expand till it reaches the top so all content is always visible.

**Comment by kathaypacific** [comment]
> > @kathaypacific it looks like we'll need to scroll on some of the wallet connect tests.
> 
> Ah weird, this bottom sheet is supposed to measure itself and expand till it reaches the top so all content is always visible.

yeah it's supposed to! i just tested on an SE and it seems okay for me. i'll rerun the CI, maybe it was a glitch / a screenshot taken during a transition
Simulator Screen Shot - iPhone SE (3rd generation) - 2023-03-17 at 09 24 54

**Comment by MuckT** [comment]
@kathaypacific looks like the WC tests are passing just a small adjustment for fiat connect tests is needed.

**Pull request merged**
