### PR TITLE
Add Universal Link support for WC

### LINKED ISSUE #1065: Fix WalletConnect universal deeplink
WalletConnect universal deeplink on mobile is not working.

Steps to reproduce on mobile (iOS):
1. Open https://app.sushi.com
2. Connect Wallet
3. Select `Connect Wallet`
4. Look for `Valora` (page 4) and tap it 

5. Notice it opens the browser to a 404 page on valoraapp.com instead of opening Valora with the WalletConnect flow

This is because the universal deeplink metadata is not setup on valoraapp.com.

Android uses `wc://` links on mobile which Valora is already registered to handle.
The OS should prompt the user to select the app to open when handling such links.
Unless the user has selected to always handle `wc://` links with a specific app.

We should check both iOS and Android handle the mobile-to-mobile flow with WalletConnect.

### PR DESCRIPTION
**Pull request by gnardini**
### Description

Added Universal Link support for both iOS and Android. Both require changes to valoraapp.com which were made in [this PR on the website](https://github.com/valora-inc/valora-website/pull/192) (it's already been deployed to production).

iOS setup was already working app-side, this PR adds support for Android as well.

### Other changes

N/A

### Tested

Manually using app.sushi.com on both Android and iOS

### How others should test

- Open https://app.sushi.com
- Tap on 'Connect to wallet'
- Select WalletConnect
- Go to the forth tab and choose Valora.
- The Valora app should open. Connection might fail since it's not using the Celo bridge but the important part is that the app is opened and not a webpage.

### Related issues

- Fixes #1065

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Cool! So WC prefers using the universal link on Android too?
If that's the case, the information on https://docs.walletconnect.org/v/2.0/mobile-linking#for-android should be updated.

**Comment by gnardini** [comment]
It doesn't, it uses something that looks like what the docs say, but since I was adding universal link support for iOS I thought there was no harm in adding it for Android as well.

What fixed this on Android is in the manifest separate the `wc` prefix from the `celo` one, otherwise it was looking for links that look like `wc://wallet`, now it accept anything that starts with `wc:`

**Comment by jeanregisser** [comment]
Great! Thanks for the clarification.

**Review by jeanregisser — APPROVED** [review]

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this task using Latest Android Internal build V1.20.1, Test flight build 1.20.1 (163277387) & updated the status in below sheet.

**Sheet Link:** https://docs.google.com/spreadsheets/d/1kJdb-eT69OM35LQUIpBKMI5MXNG-oXVaYoflX6XmGfA/edit#gid=83118437

**Devices:** iPhone 12 (14.7.1), Redmi Note 8 (10.0), iPhone 6+ (12.5.4), OnePlus 7t (11.0)

**Pull request merged**
