### PR TITLE
Add GBP and RUB local currencies and sort list alphabetically

### LINKED ISSUE #1720: Adding RUB as local currency
### What would you like?
Adding RUB as local currency

### Why is this needed?
In preparation for Russian localization

### LINKED ISSUE #1783: Add GBP to list of supported currencies

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

This is a quick addition until we can prioritize listing all fiat currencies (which requires some more changes and a search feature, see valora-inc/wallet#581).

### Other changes

Sort currencies list alphabetically so it's easier to find them.

### How others should test

GBP and RUB currencies can be used and the list is sorted alphabetically.

### Related issues

- Fixes #1783
- Fixes #1720

### Backwards compatibility

Yes

### CODE REVIEW

**Review by kathaypacific — APPROVED** [review]
🚀 nice catch!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task in Latest Android Internal Release build V:1.25.1 and Latest iOS testflight Release build V:1.25.1 and updated the status in Test rails

**Test rails link :** https://valoraapp.testrail.io/index.php?/runs/view/18&group_by=cases:section_id&group_order=asc&group_id=30

**Observation :** Search bar is not seen which is mentioned in the [PR](https://github.com/valora-inc/wallet/issues/581) and we have raised [query](https://github.com/valora-inc/wallet/issues/1898) for it 
**Devices :** Google Pixel 2XL (11.0) , iPhone 12 (14.7.1) 

**CC** @jeanregisser 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task in Latest Android Internal Release build V:1.25.2 and updated the status in Test rails

**Test rail link:**

**Android 10:** https://valoraapp.testrail.io/index.php?/tests/view/7056&group_by=cases:section_id&group_order=asc&group_id=30

**Observation**:

1. Search bar is not seen which is mentioned in the [PR]( https://github.com/valora-inc/wallet/issues/581) and we have raised [query](https://github.com/valora-inc/wallet/issues/1898) for it.

**Devices** : Samsung Galaxy M40(10.0)

**CC** @jeanregisser 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task in Latest Android Internal Release build V:1.25.2 and updated the status in Test rails

**Test rail link:**

**Android 8:** https://valoraapp.testrail.io/index.php?/tests/view/7056&group_by=cases:section_id&group_order=asc&group_id=30

**Observation:**

1. 
Search bar is not seen which is mentioned in the [PR](https://github.com/valora-inc/wallet/issues/581) and we have raised [query](https://github.com/valora-inc/wallet/issues/1898) for it.

**Devices** : Samsung Galaxy A8+(8.0)

**CC**: @jeanregisser 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task in Latest Android Internal Release build V:1.25.2 and updated the status in Test rails

**Test rail link:**
**Android 9:** https://valoraapp.testrail.io/index.php?/tests/view/7443

**Observation:** Search bar is not seen which is mentioned in the [PR](https://github.com/valora-inc/wallet/issues/581) and we have raised [query](https://github.com/valora-inc/wallet/issues/1898) for it.

**Devices:** Redmi Note 5 Pro (9.0)
**cc:** @jeanregisser 
Thanks..!!

**Pull request merged**
