### PR TITLE
Allow using any stablecoin for gas fees

### LINKED ISSUE #1747: Add support for paying fees cReal
cReal is the new 'core' stable coin that was launched recently by cLabs. It is pegged 1:1 to fiat currency Brazilian Real.
Native in this context means that it is possible to pay transaction fees in cReal in te same way as cEUR, cUSD, CELO.

While the token is supported by Valora out of the box, paying transaction fees in cReal requires additional development.

Celo foundation will do a marketing push for cReal at the end of January. If we will have full support for cReal, we can piggy back on their marketing campaigns and gain some additional traction in the market that is already second biggest for Valora.

Eng notes:
- Looks like we just need to add cREAL to the CURRENCIES list on `src/utils/currencies.ts` but that may cause other changes that need taken care of.

AC:
- [ ] It is possible to pay transaction fee in cREAL.
- [ ] Document engineering process for a adding support for new stable coins (i.e., so that an external contributor could easily do it)

### PR DESCRIPTION
**Pull request by gnardini**
### Description

We can now use any stablecoin to pay for gas fees :) It ended up taking a bit longer than expected. Here's a related PR in the blockchain-api: https://github.com/valora-inc/blockchain-api/pull/101

One exception to this is reclaiming invites. There's more work that's needed there, right now pending invites in cREAL don't even show up as a in-app notification! I'll fix reclaiming in a future PR. 

### Other changes

I'm trying to phase out the use of `Currency` when we can since it's a static enum in favor of using `coreTokens` from the selector since that allows us to add new stablecoins dynamically without an app update.

### Tested

Manually and with unit tests.

### How others should test

Try and action that signs a transaction:
- Sending
- Inviting
- Signing a tx with Wallet Connect.
- Signing a tx with dappkit (ubeswap)
- Exchanging

All should work normally!

### Related issues

- Fixes #1747

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Looking great!! Thanks! 💯

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in Latest iOS test Flight Release build V:1.25.1 and updated the status in test rails.

**Test rail link** :
**iOS13:** https://valoraapp.testrail.io/index.php?/tests/view/4409

**Devices** : iPhone 7 (13.3)
**Cc**: @gnardini 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in Latest Android Internal Release Build V:1.25.2 and updated the status in test rails.

**Test rail link :**
**Android 10:**
https://valoraapp.testrail.io/index.php?/tests/view/7090&group_by=cases:section_id&group_order=asc&group_id=30

**Devices** : Samsung Galaxy M40(10.0)

**Cc:** @gnardini 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue in Latest Android Internal Release Build V:1.25.2 and updated the status in test rails.


**Android 8:**

https://valoraapp.testrail.io/index.php?/tests/view/7153&group_by=cases:section_id&group_order=asc&group_id=30

**Observation :** Error is seen when user is trying to scan QR code from desktop for ubeswap and we have raised [bug] (https://github.com/valora-inc/wallet/issues/1285) for it 

**Devices :** Samsung Galaxy J5 Prime(8.0.0)

Cc: @gnardini
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue in Latest Android Internal Release Build V:1.25.2 and updated the status in test rails.

**Test rail links:**
**Android 9:** https://valoraapp.testrail.io/index.php?/tests/view/7477

**Observation :** Error is seen when user is trying to scan QR code from desktop for ubeswap and we have raised [bug](https://github.com/valora-inc/wallet/issues/1285) for it 

**Devices :** Redmi Note 5 Pro (9.0)
Cc: @gnardini
Thanks..!!

**Pull request merged**
