### PR TITLE
Label invite rewards correctly in the feed

### LINKED ISSUE #986: Label invite rewards correctly in the feed
### Current behavior
Rewards received from inviting others show up as "Payment received" in the feed

### Desired behavior
They should say "Reward received"

### Steps to Reproduce
Invite someone to Valora (in alfajores only for now) verify with their phone number, receive the reward and check the copy.

### Versions
All

### PR DESCRIPTION
**Pull request by gnardini**
### Description

We are now fetching the list of `inviteRewardsSenders` from Firebase to show the correct name/description from transactions coming from addresses used to distribute invite rewards.

### Other changes

- Changed `CELO_LOGO_URL` to use a jpeg with a white background.

### Tested

Manually

### How others should test

- Invite someone to Valora (in alfajores only for now) 
- Verify with their phone number and claim the money sent
- Check that you received the reward in the account you used to send the invitation
- Verify that the sender of the invite reward says "CELO Network" and the description "Reward received"

### Related issues

- Fixes #986

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R78](https://valora.testquality.com/project/12128/testcase/297911/requirement/11663).

**Comment by ValoraQA** [comment]
Hi @MuckT we have verified this task on latest flight build V1.18.0 and we are not able to complete this task because of below mentioned issue.
issue: #1009 
And we have updated out status in **testquality tool:**
-  https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469278
**Devices:** iPhone 6+(12.5.4)

**Comment by ValoraQA** [comment]
Hi @MuckT we have verified this task on latest flight build V1.18.0 and updated the status in below Testquality tool.
**TQ link:**
**iPhone 6+(12.5.4):**
- https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469278

**Devices:** iPhone 6+(12.5.4)

**Comment by ValoraQA** [comment]
Hi @MuckT we have verified this task on latest test flight build V1.18.0 and updated the status in below Testquality tool.

**Test quality tool link:**
- https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469267


**Query:**
- We have observed same issue. i.e. user redirects to App store build & forced to download app store build even we sent invitation using Alfajores build. (Please refer attachments present in above comment) 

**Verified On Devices:** iPhone SE (13.6.1)

**Pull request merged**
