### PR TITLE
fix(skip-verification): fix bug that caused Verification to show up on app kill when it was skipped by experiment

### PR DESCRIPTION
**Pull request by jh2oman**
### Description

Fixes a [bug found by QA ](https://github.com/valora-inc/wallet/issues/2183) that caused the Phone Verification screen to pop up to the user first thing when they open the app if verification was skipped by the experiment.

### Tested

Went through the flow on iOS simulator and could no longer repro the issue

### How others should test

Repro steps from https://github.com/valora-inc/wallet/issues/2183 and verify that the bug is fixed

### Related issues

- Fixes https://github.com/valora-inc/wallet/issues/2183

### CODE REVIEW

**Review by MuckT — APPROVED** [review]
Thanks for grabbing this! I tested with the reproduction steps for https://github.com/valora-inc/wallet/issues/2183 and no longer see the issue reproduce.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Alfajores build V1.29.2 & Android Alfajores Build V1.29.2 & updated status in test rails.

**Observations:**

- For iOS platform we are able to see phone number verification page when we kill the app and reopen it and also Step 4 of 3 is seen instead of Step 3 of 3.
- If we go to rewards page and click on connect number then also phone number verification page is seen. This issue is reproducible on both android & iOS platforms.
 **Reference link**: [link](https://github.com/valora-inc/wallet/issues/2183#issuecomment-1082894933)

- If we create a new account or restore account and try to access the persona flow it asks us to connect the phone number.
 **Reference Link** : [link](https://github.com/valora-inc/wallet/issues/2183#issuecomment-1080216206)

**Test rail links:**
**Android 12:** https://valoraapp.testrail.io/index.php?/tests/view/22205
**iOS13:** https://valoraapp.testrail.io/index.php?/tests/view/22250
**iOS14:** https://valoraapp.testrail.io/index.php?/tests/view/22235

**Devices:**  iPhone SE 2020 (14.8.1), iPhone 7 (13.3), Google Pixel 4a (12.0)

**CC:** @jh2oman 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT  we have verified the above issue on latest android internal Alfajores build V:1.30.1 and updated the status in test rails 

**Observation :** User is not able to see phone number screen while creating account / restoring account / clicking on link bank account / 
User is able to see phone number screen after clicking on connect number from supercharge screen

**Test Rails link:**
**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/27280

Device : Google Pixel 2XL(11.0) 

CC: @jh2oman 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Test flight Alfajores build V1.30.1 & updated status in test rails.

**Test rail link:**
**iOS15:** https://valoraapp.testrail.io/index.php?/tests/view/27218

**Device:** iPhone 13 mini(15.1.1) 

**CC:** @jh2oman 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest iOS Testflight Alfajores build V:1.30.1 and updated the status in test rails

Observation : User is not able to see phone number screen while creating account / restoring account / clicking on link bank account.
User is able to see phone number screen after clicking on connect number from supercharge screen

Test Rails link:
iOS 14 : https://valoraapp.testrail.io/index.php?/tests/view/27311

Device : iPhone 12(14.7.1)

CC: @jh2oman

Thanks..!

**Pull request merged**
