### PR TITLE
single translation file #1 - accountScreen10

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

Step 1 for single translation file:
- set up "translation" as the default namespace, and move accountScreen10 file translations to this
- remove references to "accountScreen10" in the app
- no other logic was changed

### Other changes

N/a

### Tested

Tested by restarting and clicking through the app, the translations (not translation keys) are seen

### How others should test

Same as above, particularly the account screens

### Related issues

N/A

### Backwards compatibility
N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
LGTM 👍

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing 
**Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682
**FYI:** We have checked all applications in the English language & updated the status here for BVT testing.
**Verified On Devices:**  iPhone SE(14.6), Google Pixel 2XL (11.0)
Can you please let us know if we need to test any other thing here ?
Thanks..!!
CC: @kathaypacific

**Comment by kathaypacific** [comment]
> Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing **Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682 **FYI:** We have checked all applications in the English language & updated the status here for BVT testing. **Verified On Devices:** iPhone SE(14.6), Google Pixel 2XL (11.0) Can you please let us know if we need to test any other thing here ? Thanks..!! CC: @kathaypacific

Hi team, this change was more for technical purposes - it is expected that the app behaviour/text displayed in all screens of the app is not affected :) nothing else needs to be tested aside from normal smoke/regression testing.

**Comment by ValoraQA** [comment]
> > Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing **Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682 **FYI:** We have checked all applications in the English language & updated the status here for BVT testing. **Verified On Devices:** iPhone SE(14.6), Google Pixel 2XL (11.0) Can you please let us know if we need to test any other thing here ? Thanks..!! CC: @kathaypacific
> 
> Hi team, this change was more for technical purposes - it is expected that the app behaviour/text displayed in all screens of the app is not affected :) nothing else needs to be tested aside from normal smoke/regression testing.

Thank you @kathaypacific for confirmation:)

**Comment by ValoraQA** [comment]
https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586686

> > Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing **Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682 **FYI:** We have checked all applications in the English language & updated the status here for BVT testing. **Verified On Devices:** iPhone SE(14.6), Google Pixel 2XL (11.0) Can you please let us know if we need to test any other thing here ? Thanks..!! CC: @kathaypacific
> 
> Hi team, this change was more for technical purposes - it is expected that the app behaviour/text displayed in all screens of the app is not affected :) nothing else needs to be tested aside from normal smoke/regression testing.

Hey, @kathaypacific We have completed [BVT]( https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586682) in test quality tool. Can you please let us know if we need to perform regression testing on v1.22.2?
CC: @MuckT

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using Android internal build and iOS test flight build V:1.22.2 & updated status in the test quality tool while performing BVT testing
**Test Quality Tool:** https://valora.testquality.com/project/12128/plan/20403/run/153467/result/2586686
FYI: We have checked all applications in the English language & updated the status here for BVT testing.
**Verified On Devices:** Samsung Galaxy J5 Prime (8.0)
Thanks..!!
CC: @kathaypacific

**Pull request merged**
