### PR TITLE
Make reward pill text remote configurable

### LINKED ISSUE #1167: Make reward pill remote configurable

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Make reward pill text remote configurable

### Other changes
N/A

### Tested
Manually

### How others should test
N/A

### Related issues
- Fixes #1167

### Backwards compatibility
Yes

### CODE REVIEW

**Review by jeanregisser — COMMENTED** [review]
Thanks!

In the future we also want to allow Over-The-Air updates with Crowdin, so this won't be needed anymore: https://github.com/valora-inc/wallet/issues/1059

**Review by gnardini — APPROVED** [review]
Thanks for implementing this! Like @jeanregisser said, can't wait for Crowdin OTA updates to avoid this kind of work in the future :)

**Comment by ValoraQA** [comment]
Hey @MuckT Can you please let us know if we have to test anything from our side.

Thanks!!
CC: @tarikbellamine

**Comment by MuckT** [comment]
@ValoraQA Nothing to test here outside of normal the build verification tests.

**Pull request merged**
