### PR TITLE
fix: manage the abort callback more elegantly

### PR DESCRIPTION
**Pull request by nicolasbrugneaux**
### Description

This changes the way the `abort` method is called when the component unmounts. Right now it actually sends an abort after each success which isn't ideal..

### Other changes

Fixed a typo in the english translation

### Tested

via ios ismulator

### How others should test

The payment shouldn't be aborted after a success

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Review by MuckT — APPROVED** [review]
Was able to process to purchase several items on https://prod-celo-demo-store.demo.firstdag.com one after another without issue.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Test Flight Release build V1.29.2 & Android Internal Release Build V1.29.2 and updated status in test rails.

**Observations**:

- "Your payment failed to submit" error appears and transaction fails & user redirects to home screen when user taps on Send button and complete sending flow after scanning QR code from merchant payment website.
- **Reference link:** [link](https://github.com/valora-inc/wallet/issues/2155#issuecomment-1083050068)

- “There was an error loading..” error is displayed when the user tries to scan the QR code from Merchant Payment url while creating the account while skipping the phone number, hence we have raised a bug for that.
**New Bug:** [link](https://github.com/valora-inc/wallet/issues/2275)

**Test rail links:**

**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/22230
**Android 12:**https://valoraapp.testrail.io/index.php?/tests/view/22215
**iOS13:** https://valoraapp.testrail.io/index.php?/tests/view/22260
**iOS14:** https://valoraapp.testrail.io/index.php?/tests/view/22245

**Devices:** Google Pixel 2XL (11.0), iPhone SE 2020 (14.8.1), iPhone 7 (13.3), Google Pixel 4a (12.0)
**CC:** @nicolasbrugneaux 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Test Flight Release build V1.30.1 & Android Internal Release Build V1.30.1 & updated status in test rails.

**Observation:**

- User is able to complete merchant payment flow by given [url](https://prod-celo-demo-store.eu-west-1.demo.firstdag.com/) by scanning QR code & order get placed by confirming phone number.

**Test rail links:**
**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/27297
**iOS15:** https://valoraapp.testrail.io/index.php?/tests/view/27235

**Devices:** Google Pixel 2XL (11.0), iPhone 13 mini(15.1.1)

**CC:** @nicolasbrugneaux 

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Test Flight Release build V1.30.1 updated status in test rails.

Observation:

User is able to complete merchant payment flow by given [url](https://prod-celo-demo-store.eu-west-1.demo.firstdag.com/) by scanning QR code & order get placed by confirming phone number.

Test rail links:

iOS14: https://valoraapp.testrail.io/index.php?/tests/view/27328

Devices: iPhone 12(14.7.1)

CC: @nicolasbrugneaux

Thanks..!!

**Pull request merged**
