### PR TITLE
add custom navigator options for bank account page

### PR DESCRIPTION
**Pull request by lisaqyli**
### Description
Fixes: #2108 
I separate out the fix for the navigation from this PR: https://github.com/valora-inc/wallet/pull/2161
I found out the way to clear navigation stack and replace with another screen does not work in this case b/c Settings screen does not belong to the settingsStack (defined in Navigator.tsx). It's already defined in DrawerNavigator so initiate another instance of Settings  would cause trouble. so solving the problem by customizing the header of bankAccount screen instead

### Tested

Manually and unit tested.

### CODE REVIEW

**Review by jh2oman — COMMENTED** [review]
@lisaqyli Does this also cover the "swipe back" on iOS or the hardware back button on Android? I'm worried users will still be able to get to the SyncBankAccount screen using those features

**Comment by lisaqyli** [comment]
@jh2oman no it doesn't.  I just pushed something to prevent hardware press back. It works well on Android but it's a bit suboptimal on iOS (it would disable all swipe backs even if user comes from settings page).

wdyt?

**Comment by jh2oman** [comment]
@lisaqyli I feel like there must be a better way of going about it. Can you ask people on the retentions squad? I'm really not familiar enough with these react native navigation apis to suggest something

**Review by jh2oman — APPROVED** [review]

**Comment by MuckT** [comment]
@lisaqyli Does this need to be tested by QA during the release cycle?

**Pull request merged**
