### PR TITLE
feat: add support for Polish Zloty

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

As the title

### Other changes

N/A

### Tested

Manually

### How others should test

PLN (Polish Zloty) should be available in the currencies in settings, selecting this should display all fiat currencies in PLN in the app.

### Related issues

- Fixes RET-387

### Backwards compatibility

Yes

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
🇵🇱 👍

**Review by dievazqu — APPROVED** [review]

**Comment by kathaypacific** [comment]
@mergifyio refresh

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above issue on Latest Test Flight Release Build V1.40.0 and updated the status in test rails.

**Observation**:
- Currency symbol does not change on recent transaction activity after selecting different currency and we have raised bug for it.

**Existing Bug link:** https://github.com/valora-inc/wallet/issues/2507

**Test Rail link:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/69483

**Device**: iPhone 13 mini(15.1.1)

**CC**: @kathaypacific 

Thanks.!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above task on Latest Android Internal Release Build V1.40.0 and updated the status in test rails.

**Test Rail link:**
**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/69545

Device: Google Pixel 2XL(11.0)

CC: @kathaypacific

Thanks.!!

**Pull request merged**
