### PR TITLE
feat(buttons): Change onboarding buttons to new design

### PR DESCRIPTION
**Pull request by finnian0826**
### Description

Update the onboarding buttons

### Test plan

unit/e2e tests pass

Manual Tests:
Simulator Screenshot - iPhone 14 Pro - 2024-05-16 at 12 33 56
Simulator Screenshot - iPhone 14 Pro - 2024-05-16 at 12 34 02
Simulator Screenshot - iPhone 14 Pro - 2024-05-16 at 12 34 25

### Related issues

- N/A

### Backwards compatibility

Yes

### Network scalability

If a new NetworkId and/or Network are added in the future, the changes in this PR will:

- [X] Continue to work without code changes, OR trigger a compilation error (guaranteeing we find it when a new network is added)

### CODE REVIEW

**Comment by finnian0826** [comment]
The paste button on restore wallet looks a bit weird, should that one stay as the old version?

**Comment by satish-ravi** [comment]
> The paste button on restore wallet looks a bit weird, should that one stay as the old version? It feels weird to keep around the style for just one use case, but I'm not seeing any other way to override color to white.

Looks like this sets the a rounded: false property, but the gray with border doesn't seem to honor it and always sets a borderRadius. I'd suggest we fix this if its simple, or leave onboarding_secondary as deprecated and use it in one place, with a follow up ticket

**Comment by finnian0826** [comment]
Kept onboarding secondary as it was used for the paste button and looks weird in a different style, added a follow-up ticket for removing the deprecated style: https://linear.app/valora/issue/ACT-1200/placeholder-remove-deprecated-onboarding-button-style

**Review by MuckT — APPROVED** [review]
Thanks for catching the undesired change with the paste button!

**Pull request merged**
