### PR TITLE
Fix SendConfirmation screen insufficient funds bug

### PR DESCRIPTION
**Pull request by jh2oman**
### Description

Load the balance only once for the SendConfirmationScreen so that it doesn't pick up any balance changes from completed transactions and potentially throw an error.

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

I couldn't come up with an easy way to add a unit test for this bug, suggestions welcome! 

Manually test by following the repro steps on https://github.com/valora-inc/wallet/issues/1341 and seeing that the bug no longer repros. 

### Related issues

- Fixes # https://github.com/valora-inc/wallet/issues/1341

### Backwards compatibility

The balance is never refreshed during this flow anyways, so there should be no unintended side effects from only loading it once.

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
Small nit, looks great, thanks for debugging and fixing this!

I don't think it's necessary to add a unit test for this because this code will go away soon, but if you did want to test this you would need to call `rerender` I think, there are a couple of examples in the codebase.

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified the issue on latest Android Internal build V:1.22.0 and latest iOS Test Flight build V:1.22.0 and updated the observation in Gsheet 

Link : https://docs.google.com/spreadsheets/d/1UVmYHl_g7ZWKqX3zBtc5OdO9wEmdAdj4PW9zgwJxUys/edit#gid=603719806
Note : We are not able to complete send flow as error is seen while performing send flow 

New Bug Link : https://github.com/valora-inc/wallet/issues/1438

CC: @jh2oman

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified the issue on the latest Android Internal build V:1.22.0 and iOS Test Flight build V:1.22.0 and updated the observation in Gsheet

**Link :** https://docs.google.com/spreadsheets/d/1UVmYHl_g7ZWKqX3zBtc5OdO9wEmdAdj4PW9zgwJxUys/edit#gid=603719806

**Devices :** Samsung Galaxy J5 Prime (8.0), iPhone 12(15), Redmi Note 8 (10.0)

CC: @jh2oman

**Comment by ValoraQA** [comment]
Hi @MuckT we have verified the above issue in the latest iOS Test Flight build V: 1.22.0 and updated status in Test Quality Tool
Link :  https://valora.testquality.com/project/12128/plan/22712/run/152953/result/2573241
Verified on devices : iPhone SE (13.6.1)
CC: @jh2oman

**Pull request merged**
