### PR TITLE
Add support link to invite rewards banner

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

Instead of T&Cs for this beta program, we are going with a support article.

Screenshot 2022-05-11 at 10 25 34

### Other changes

N/A

### Tested

Manually

### How others should test

On the invite rewards banner, tapping on the linked text should open the expected support article.

### Related issues

N/A
### Backwards compatibility

Yes

### CODE REVIEW

**Comment by kathaypacific** [comment]
@jeanregisser want to get your opinion to sanity check my OCD...this is the design
Screenshot 2022-05-11 at 10 26 42

notice how the underline is like 1 pixel below the text. but with the RN styles, the text decoration underline is like so close to the text. it is making me feel sad but i don't know if it's worth hacking the component (create a view with a border bottom around the text or something) - what do you think?

**Comment by kathaypacific** [comment]
Although not blocking for now, we do need to merge the website redirect PR to ensure the link actually loads something. Just reminding myself

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest iOS Test flight Alfa jores Build, Android Alfa jores Build V1.32.0 & updated status in test rails.

**Observation:**
- “Confirmation error” popup appears when user tries to connect phone number after creating account, so user is not able to confirm the phone number.

**New Bug :** [link](https://github.com/valora-inc/wallet/issues/2467)

**Test rail links:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/33522
**Android 10:** https://valoraapp.testrail.io/index.php?/tests/view/33537

**Devices:** iPhone 13 mini(15.1.1), Google Pixel XL (10.0)

**CC:** @kathaypacific 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest iOS Test flight Alfa jores Build V1.32.0 & updated status in test rails.

**Observation**

- Confirmation error is seen when user is connected to US VPN and tries to connect number
- Confirmation error is seen when user is not connected to VPN but tries to connect using US number

**New Bug :** https://github.com/valora-inc/wallet/issues/2467

**Test rail links:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/33522
**iOS 14:** https://valoraapp.testrail.io/index.php?/tests/view/33507

**Devices:** iPhone 13 mini(15.1.1), iPhone 12 (14.7.1)

CC: @kathaypacific

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Android Internal Alfajores Build V1.32.1 & updated status in test rails.


Test rail links:

Android 10: https://valoraapp.testrail.io/index.php?/tests/view/33537
Android 11: https://valoraapp.testrail.io/index.php?/tests/view/33552

Devices: Google Pixel 2XL(11.0), Samsung Galaxy M31(10.0)

CC: @kathaypacific

Thanks..!!

**Pull request merged**
