### PR TITLE
Improve UX when a user types last 4 account digits when checking account from contact

### PR DESCRIPTION
**Pull request by Pedro-vk**
### Description

_When the user types a digit on any of the 4 inputs, it goes to next input_

### Tested

_Is necessary to send any asset to a phone number with 2 or more accounts_

### How others should test

_Send any asset to a phone with 2 or more accounts_

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/4116

### CODE REVIEW

**Review by gnardini — COMMENTED** [review]
Working great on iOS but it's not skipping to the next input on Android unfortunately :(

**Comment by Pedro-vk** [comment]
> Working great on iOS but it's not skipping to the next input on Android unfortunately :(

I've developed it on Android and is working fine on Samsung Galaxy s10e with Android 11. What is your device? and do you have any idea of what could produce it? the changes are very simple

**Comment by MuckT** [comment]
@Pedro-vk is this branch ok to update? If so I can retest the secure send on Android.

**Comment by jeanregisser** [comment]
Stale PR, closing.

**Pull request closed without merging**
