### PR TITLE
Add RU/FR/IT to supported languages

### LINKED ISSUE #1721: Adding IT, RU, FR language support
### What would you like?
Adding IT, RU, FR language support - ideally for 1.25

### Why is this needed?
Working on localization into these languages to enhance UX for European users

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

Add RU/FR/IT to supported languages. Please note that the translations for these 3 new languages are currently incomplete (many keys are still using english in the translation files) but now RU/FR/IT should appear as options in the language selection pages on app start/settings screen. 

### Other changes

N/A

### Tested

Manually verify that the new languages can be selected from and the app changes languages on selection.

### How others should test

Same as above

### Related issues

- Fixes #1721 

### Backwards compatibility

Yes

### CODE REVIEW

**Review by jeanregisser — COMMENTED** [review]
Awesome! 
There's one more thing for iOS, we need to manually add the new languages in the Xcode project. This way the App Store recognizes these new languages and the right translations for plist strings are used (for system permission popups).

Screenshot 2022-01-18 at 12 04 42

**Comment by kathaypacific** [comment]
> Awesome! There's one more thing for iOS, we need to manually add the new languages in the Xcode project. This way the App Store recognizes these new languages and the right translations for plist strings are used (for system permission popups).
> 
> Screenshot 2022-01-18 at 12 04 42

Ah thank you for pointing this out! i have updated :)

**Review by jeanregisser — APPROVED** [review]
Merci

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest Android Internal Release build and Latest iOS Test Flight Release build V:1.25.1 and updated the status in Gsheet

**Sheet link :** 
- https://docs.google.com/spreadsheets/d/1_eusrRjJCC9pvOcHaSEbw7P515xBb9yB659pr_8O8Cw/edit#gid=1616260500

**Observation :** RU/FR/IT languages are seen after launching the application and also if user goes to setting page to change the language 

**Devices :** Google Pixel 2XL(11.0) , iPhone 12 (14.7.1)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task on Latest iOS Test Flight Release build V:1.25.1 and updated the status in test rails

**Test rail link** :

**iOS 13:** https://valoraapp.testrail.io/index.php?/tests/view/4383&group_by=cases:section_id&group_order=asc&group_id=30&group_by=cases:section_id&group_order=asc&group_id=30
[Bug Link](https://github.com/valora-inc/wallet/issues/931)

**Devices** : iPhone 7 (13.3)

Cc: @kathaypacific 

Thanks..!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the task on Latest iOS Test Flight Release build V:1.25.1 and updated the status in test rails as below.

**Test rail link :**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/4446

**Devices :** iPhone 13 mini (15.1.1)
Cc: @kathaypacific
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the task on Latest Android Internal Release build V:1.25.2 and updated the status in test rails as below.

**Test rail link**:
**Android 10:** https://valoraapp.testrail.io/index.php?/tests/view/7064&group_by=cases:section_id&group_order=asc&group_id=30

[Bug link
](https://github.com/valora-inc/wallet/issues/931)
**Devices:** Samsung Galaxy M40(10.0)

**Cc:** @kathaypacific 
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the task on Latest Android Internal Release build V:1.25.2 and updated the status in test rails as below.

**Android 9:** 

https://valoraapp.testrail.io/index.php?/tests/view/7127&group_by=cases:section_id&group_order=asc&group_id=30

**Observation** : Language page does not appear on opening the app and [bug](https://github.com/valora-inc/wallet/issues/931) is already raised for it 

Devices: Samsung Galaxy J5 Prime (8.0.0)

Cc: @kathaypacific
Thanks..!!

**Pull request merged**
