### PR TITLE
remove direct calls to i18n.t when useTranslation hook is available

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

We should avoid calling the `t` function from i18n directly, because the imported `i18n` instance could be uninitialised depending on when it was imported. This causes empty or raw translation keys to be rendered in edge cases (see https://github.com/valora-inc/wallet/issues/1557 and https://github.com/valora-inc/wallet/pull/1561)

This PR makes the easy changes, to use the `t` function from the useTranslation hook when possible. We will need to find some ways of handling places where we do translations in .ts files and static functions (like navigation options) in the future.

### Other changes

N/A

### Tested

Manually tested the affected screens to see translations are still coming through

### How others should test

Same as above

### Related issues

N/A

### Backwards compatibility

N/A

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Great! Much better thanks! 💯

**Comment by ValoraQA** [comment]
Hi @MuckT , We have verified this issue using Android Internal Build V1.23.0 , iOS Test flight build V1.23.0 & updated status in below Gsheet.

**Sheet Link:**
https://docs.google.com/spreadsheets/d/15Z15zu4roT6XFD1dbi9__c3Q6aQZpIiIZka1rKVrCgw/edit#gid=1460431754

**Observation** : User is able to see the action request page translated properly when selected language other than English language 

**Devices:** iPhone 13 mini (15.1.1), One Plus 7T(11.0)
**CC:** @kathaypacific 

Thanks..!!

**Comment by ValoraQA** [comment]
Hi @MuckT , We have verified this issue using Android Internal Build V1.23.0 , iOS Test flight build V1.23.0 & updated status in below Gsheet.

**Sheet Link:**
https://docs.google.com/spreadsheets/d/15Z15zu4roT6XFD1dbi9__c3Q6aQZpIiIZka1rKVrCgw/edit#gid=1460431754

**Observation:** User is able to see the action request page translated properly when selected language other than English language

Devices: Samsung Galaxy M40 (10.0), iPhone SE (14.2)
CC: @kathaypacific 
Thanks..!!

**Comment by ValoraQA** [comment]
Hi @MuckT , We have verified this issue using Android Internal Build V1.23.0 & updated status in below Gsheet.

**Sheet Link** :
https://docs.google.com/spreadsheets/d/15Z15zu4roT6XFD1dbi9__c3Q6aQZpIiIZka1rKVrCgw/edit#gid=1460431754

**Observation** : User is able to see the action request page translated properly when selected language other than English language

**Devices** : Samsung Galaxy A8+(8.0), Redmi Note 5 Pro (9.0)
CC: @kathaypacific 
Thanks..!!

**Pull request merged**
