### PR TITLE
Deprecate recoverEIP712TypedDataSigner

### PR DESCRIPTION
**Pull request by isabellewei**
### Description

The function `recoverEIP712TypedDataSigner` has been deprecated, more details here: https://github.com/celo-org/celo-monorepo/pull/8836 This PR uses `verifyEIP712TypedDataSigner` instead.

### Tested

Not tested

### How others should test

Receive a transaction from someone and attempt to look at their profile picure/name

### Backwards compatibility

Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]
🚀

**Comment by ValoraQA** [comment]
Hi @MuckT, We have verified this issue using Android Internal Build V1.23.0 and iOS Test flight build V1.23.0 & updated status in below Gsheet.

**Sheet Link** :
https://docs.google.com/spreadsheets/d/15Z15zu4roT6XFD1dbi9__c3Q6aQZpIiIZka1rKVrCgw/edit#gid=691183073

**Bug Link** :
https://github.com/valora-inc/wallet/issues/1637


**Devices** : iPhone 13 mini (15.1.1), iPhone 7(13.3), Samsung Galaxy A8+(8.0)

CC: @isabellewei 
Thanks..!!

**Comment by ValoraQA** [comment]
Hi @MuckT, We have verified this task using iOS Test flight build V1.23.0 & Android Internal build V:1.23.0 and updated status in below Gsheet.

**Sheet Link :**
https://docs.google.com/spreadsheets/d/15Z15zu4roT6XFD1dbi9__c3Q6aQZpIiIZka1rKVrCgw/edit#gid=691183073

**Bug Link :** [#1637](https://github.com/valora-inc/wallet/issues/1637)
**Observation :** When User A sends amount to User B then User B is not able to see User A profile picture (if uploaded)

**Devices :** Samsung Galaxy M40 (10.0), One plus 7t (11.0), iPhone 13 mini (15.1.1), iPhone SE (14.2)

CC: @isabellewei 
Thanks..!!

**Comment by ValoraQA** [comment]
Hi @MuckT, We have verified this task using Android Internal build V:1.23.0 and updated status in below Gsheet.

**Sheet Link** :
https://docs.google.com/spreadsheets/d/15Z15zu4roT6XFD1dbi9__c3Q6aQZpIiIZka1rKVrCgw/edit#gid=691183073

**Bug Link** : #1637
**Observation** : When User A sends amount to User B then User B is not able to see User A profile picture (if uploaded)

**Devices** : Samsung Galaxy A8+(8.0)

CC: @isabellewei 
Thanks..!!

**Pull request merged**
