### PR TITLE
fix: show view assets button all the time

### PR DESCRIPTION
**Pull request by Samuel3Shin**
### Description

Showing `View Assets` button all the time. 

before: only shows the `View Assets` button when the user has more than 1 token. It causes a problem that users can't see an NFT viewer banner on the view assets page.

Screen Shot 2022-08-18 at 2 51 53 PM

after: showing it if the user has at least one token.
Screen Shot 2022-08-18 at 2 52 09 PM

### Other changes
N/A

### Tested
with iOS emulator

### How others should test
With emulator

### Related issues
- Fixes [#[slack thread]](https://valora-app.slack.com/archives/C029Z1QMD7B/p1660856649532699)

### Backwards compatibility
Yes

### CODE REVIEW

**Comment by MuckT** [comment]
@Samuel3Shin looks like a few tests need to be updated. Also should we display some text on the empty asset list @ellenwoconnor?

**Comment by MuckT** [comment]
@jh2oman - Does updated the expected results for local currency fetch have any issues to your knowledge?

**Review by kathaypacific — APPROVED** [review]

**Comment by dievazqu** [comment]
I guess the same can happen if the user doesn't have any money but receives a NFT.

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above task on Latest Test Flight Release Build V1.40.0 and updated the status in test rails.

**Observation**:
- User is able to see View assets button even if the user have single token in the account
- On tapping on view assets button user is able to see NFT banner below balance amount and also able to see the single token with balance.

**Test Rail link:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/69497

**Device**: iPhone 13 mini(15.1.1) 

**CC**: @Samuel3Shin 

Thanks.!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified the above task on Latest Android Internal Release Build V1.40.0 and updated the status in test rails.

**Observation**:
- User is able to see View assets button even if the user have single token in the account
- On tapping on view assets button user is able to see NFT banner below balance amount and also able to see the single token with balance.

**Test Rail link:**
**Android 12:** https://valoraapp.testrail.io/index.php?/tests/view/69590

**Device**: Google Pixel 4a(12.0)

**CC**: @Samuel3Shin

Thanks.!!

**Pull request merged**
