### PR TITLE
fix: bottom sheet not displaying second time after dismiss

### LINKED ISSUE #2245: Multi-token pop-up is not appearing a second time after the user tries to change the token on the enter amount page.
**Frequency:** 100%

**Repro on build version:** Android Internal Release Build V1.29.0, iOS Test flight Release Build V1.29.0 
**Repro on devices:** iPhone 13 mini (15.1.1), Samsung Galaxy A9 Pro(8.0), iPhone 12(14.7.1), Samsung Galaxy F41 (11.0)

**Does Not Repro on build version:** Android Internal Release Build V1.28.1, iOS Test flight Release Build V1.28.1 
**Does Not Repro on devices:** iPhone 12(14.7.1), iPhone 13 mini (15.1.1), Google Pixel 2XL(11.0)

**Pre-condition:** 

 1. User must have installed the application and completed the onboarding flow.
 2. User must have multiple tokens balance in the account.
 3. User must be on the enter amount screen.
 
**Repro Steps:**

 1. Enter the amount in the field.
 2. Tap on Select token pop-up and select the token.
 3. Again enter the amount in the field.
 4. Tap on select token pop-up and observe.
 
**Bug:** Multi-token pop-up is not appearing a second time after the user tries to change the token on the enter amount page.

**Expected Behavior:** Multi-token pop-up should appear second time when user tries to change the token on the enter amount page.

**Investigation:**

 1. For request flow also multi-token pop-up is not appearing a second time after the user tries to change the token on the enter amount page.
 2. When user clicks on the same Dapp section for second time pop-up is not appearing and same is also happening for recent Dapp section. [Dapp.mp4](https://drive.google.com/file/d/1OxE6CQRuYsIVPpQjGZ8SeEHzNLiSv5rE/view?usp=sharing) 
 
.**Impact:** Bad user impact as user is not able to select the token for the second time.
 
**Attachment:** [Select Token.mp4](https://drive.google.com/file/d/13YJOZqyvAniVNCsrLBPiWMF8hWPla4Zh/view?usp=sharing)

### PR DESCRIPTION
**Pull request by MuckT**
### Description

The bottom sheet was not displaying a second time after being dismissed as described in #2245. This aims to fix that issue on wherever the `BottomSheet.tsx` is used such as the Dapps page and token bottom sheet.

### Other changes

N/A

### Tested

Tested locally on Android 10 & Android 5 in dev and release mode.

### How others should test

Follow the reproduction steps for #2245 and ensure that the issue does not reproduce.
Follow the reproduction steps for #1973 and ensure that the issue does not reproduce.
Follow the testing steps for #2230.

### Related issues

- Fixes #2245

### Backwards compatibility

Yes

### CODE REVIEW

**Review by kathaypacific — CHANGES_REQUESTED** [review]
I was curious about the flicker comment for the opacity style, and i can indeed see it (especially with slow animations, vid attached) so i think that we should not remove the opacity style here.

https://user-images.githubusercontent.com/20150449/160362467-2966f06f-344a-41a2-ad66-96fdcf60f8b6.mov




I think the issue is that the `pickerHeight` value is not being correctly set to 0 after a dismiss event, i don't really know why as this is being controlled by the `Animated.ScrollView`. i think something you can do instead is manually set the `pickerHeight` to 0 in the `useShowOrHideAnimation` hook, something like 
```
  useShowOrHideAnimation(
    progress,
    isVisible,
    () => setOptionsVisible(true),
    () => {
      setPickerHeight(0)
      setOptionsVisible(false)
    }
  )
```

what do you think?

**Review by jeanregisser — COMMENTED** [review]
Erf weird 🤔 

The flicker fix was introduced in 1.26. This issue was introduced in 1.29.
I highly suspect the reanimated upgrade in #2230 broke this, given there were no changes in BottomSheet since Feb 10th.

Apparently `pickerHeight` stays at 0 the second time or something, which makes it stay hidden.

**Comment by MuckT** [comment]
@kathaypacific and @jeanregisser I've incorporated the changes @kathaypacific suggested and it appears to be working as intended now without the flicker!

**Review by kathaypacific — APPROVED** [review]
🚀

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above task on Latest Test Flight Release build V1.29.2, Android Internal Release Build V1.29.2, Test Flight Alfajores Build V 1.29.2 and Android Alfajores Build V 1.29.2 & updated status in test rails.

**Test rail links:**

**Android 11:** https://valoraapp.testrail.io/index.php?/tests/view/22225
**Android 12:** https://valoraapp.testrail.io/index.php?/tests/view/22210
**iOS13:** https://valoraapp.testrail.io/index.php?/tests/view/22255
**iOS14:** https://valoraapp.testrail.io/index.php?/tests/view/22240

**Devices:** Google Pixel 2XL (11.0), iPhone SE 2020 (14.8.1), iPhone 7 (13.3), Google Pixel 4a (12.0)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Test Flight Release build V1.30.1 and Test Flight Alfajores Build V 1.30.1 & updated status in test rails.

**Test rail link:**
**iOS15:** https://valoraapp.testrail.io/index.php?/tests/view/27224

**Device:** iPhone 13 mini(13.1.1)

Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Test Flight Release build V1.30.1 and Test Flight Alfajores Build V 1.30.1 & updated status in test rails.

Test rail link:
iOS14:  https://valoraapp.testrail.io/index.php?/tests/view/27317

Device: iPhone 12 (14.7.1)
Thanks..!!

**Pull request merged**
